const COLUMN_LABELS = {
  id: 'Identifiant',
  name: 'Désignation',
  title: 'Titre',
  description: 'Description',
  person_name: 'Salarié',
  employee_id: 'Salarié',
  user_id: 'Utilisateur',
  status: 'Statut',
  type: 'Type',
  severity: 'Gravité',
  score: 'Note',
  risk_score: 'Score de risque',
  overall_score: 'Note globale',
  decision: 'Décision',
  designation: 'Désignation',
  created_at: 'Date de création',
  updated_at: 'Dernière modification',
  occurred_at: 'Date de l’événement',
  received_date: 'Date de réception',
  detected_at: 'Date de détection',
  completed_at: 'Date de réalisation',
  completed_date: 'Date de réalisation',
  closed_at: 'Date de clôture',
  resolution_date: 'Date de résolution',
  due_date: 'Échéance',
  target_date: 'Date cible',
  review_date: 'Date de revue',
  next_review_date: 'Prochaine revue',
  next_due_date: 'Prochaine échéance',
  survey_date: 'Date de l’enquête',
  evaluation_date: 'Date d’évaluation',
  recorded_at: 'Date du relevé',
  planned_date: 'Date planifiée',
  lost_days: 'Jours d’arrêt',
  root_cause: 'Cause racine',
  treatment_plan: 'Plan de traitement',
  customer_satisfied: 'Client satisfait',
  linked_capa_id: 'CAPA liée',
  required_job_titles: 'Postes concernés',
  state: 'État',
  person: 'Personne',
  person_key: 'Identifiant personne',
  training_title: 'Formation',
  training_id: 'Identifiant formation',
  _expired: 'Formation expirée',
  _missing: 'Formation jamais suivie',
  _due_soon: 'Échéance sous 60 jours',
  _up_to_date: 'Formation à jour',
  _days_overdue: 'Jours de retard',
  __snapshot__: 'Photo à date',
  _is_open: 'Élément ouvert',
  _is_closed: 'Élément clôturé',
  _is_overdue: 'Échéance dépassée',
  _on_time: 'Dans les délais',
  _resolution_days: 'Délai de résolution (jours)',
  _open_age_days: 'Ancienneté (jours)',
  _reopened: 'Rouverte',
  _no_root_cause: 'Cause racine absente',
  _customer_dissatisfied: 'Client insatisfait',
  _resolved_no_feedback: 'Sans retour client',
  _severe_no_capa: 'Grave sans CAPA',
  _is_done: 'Terminée',
  _with_lost_time: 'Avec arrêt de travail',
  _high_untreated: 'Risque élevé non traité',
  _no_plan: 'Plan de traitement absent',
  _review_overdue: 'Revue en retard',
  _handled: 'Risque maîtrisé',
  _latest_score: 'Dernière note',
  _below_threshold: 'Sous le seuil',
  _never_evaluated: 'Jamais évalué',
  _to_replace: 'À remplacer',
  _review_due_soon: 'Revue sous 60 jours',
  _no_review_schedule: 'Date de revue absente',
  _significant_no_ccp: 'Danger significatif sans CCP',
  _within_limits: 'Dans les limites',
  _deviation: 'Écart',
  _deviation_no_capa: 'Écart sans CAPA',
  _overdue: 'En retard',
  _stalled: 'À l’arrêt',
  _cycle_days: 'Durée du cycle (jours)',
  _no_capa: 'Sans CAPA',
  _unresolved: 'Non soldée',
  _stuck_in_review: 'Bloquée en relecture',
  _pending: 'En attente',
  _pending_age_days: 'Ancienneté (jours)',
};

const VALUE_LABELS = {
  valid: 'À jour',
  due_soon: 'À renouveler bientôt',
  expired: 'Expirée',
  missing: 'Jamais suivie',
  true: 'Oui',
  false: 'Non',
  '1': 'Oui',
  '0': 'Non',
};

export function evidenceColumnLabel(column) {
  if (COLUMN_LABELS[column]) return COLUMN_LABELS[column];
  return String(column || '')
    .replace(/^_/, '')
    .replace(/__/g, '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export function evidenceValueLabel(value, column) {
  if (value === null || value === undefined || value === '') return '—';
  if (VALUE_LABELS[String(value).toLowerCase()]) return VALUE_LABELS[String(value).toLowerCase()];
  if (column === 'state') return String(value).replaceAll('_', ' ');
  return String(value);
}
