import { getAvailableProblemModules } from './problemGuide.js';
import { COMMON_SITUATIONS, PROFILE_SITUATIONS, SECTOR_SITUATIONS } from './problemSectorSituations.js';

const compareLabels = (left, right) => left.label.localeCompare(right.label, 'fr', { sensitivity: 'base' });

const MODULE_PATHWAYS = {
  accident: ['accidents', 'risks', 'qqoqccp'],
  corrective: ['capas', 'qqoqccp', 'planning', 'kpis'],
  complaint: ['complaints', 'customer-satisfaction', 'qqoqccp', 'capas'],
  conformity: ['nonconforming-outputs', 'qqoqccp', 'capas'],
  document: ['documents', 'procedures'],
  training: ['trainings', 'employees', 'procedures'],
  supplier: ['suppliers', 'nonconforming-outputs', 'capas'],
  delay: ['nonconforming-outputs', 'planning', 'qqoqccp', 'kpis'],
  risk: ['risks', 'planning'],
  procedure: ['procedures', 'nonconforming-outputs', 'capas'],
  recurring: ['capas', 'nonconforming-outputs', 'qqoqccp', 'kpis'],
  food: ['nonconforming-outputs', 'haccp', 'risks', 'qqoqccp'],
  audit: ['audits', 'capas', 'documents'],
  improvement: ['pdca', 'kpis', 'planning'],
  measurement: ['kpis', 'qqoqccp', 'pdca'],
};

const COMMON_PROBLEMS = [
  ['accident', 'Accident du travail ou presque-accident', 'accident'],
  ['corrective', 'Action corrective à mettre en place', 'corrective'],
  ['audit', 'Écart identifié lors d’un audit interne', 'audit'],
  ['supplier', 'Fournisseur ou prestataire non satisfaisant', 'supplier'],
  ['training', 'Manque de formation ou de compétence', 'training'],
  ['document', 'Document manquant, obsolète ou non maîtrisé', 'document'],
  ['procedure', 'Procédure ou consigne non respectée', 'procedure'],
  ['recurring', 'Problème récurrent malgré les corrections', 'recurring'],
  ['conformity', 'Produit ou prestation non conforme', 'conformity'],
  ['complaint', 'Réclamation ou insatisfaction client', 'complaint'],
  ['delay', 'Retard de réalisation ou de livraison', 'delay'],
  ['risk', 'Risque identifié dans l’activité', 'risk'],
  ['measurement', 'Résultats ou indicateurs en dégradation', 'measurement'],
  ['improvement', 'Organisation ou processus à améliorer', 'improvement'],
];

const SECTOR_PROFILES = {
  agriculture: [
    ['crop', 'Culture endommagée ou rendement insuffisant', 'conformity'],
    ['treatment', 'Erreur de traitement ou de dosage agricole', 'conformity'],
    ['harvest', 'Lot récolté non conforme', 'conformity'],
    ['trace', 'Traçabilité des parcelles ou des récoltes incomplète', 'document'],
    ['water', 'Risque lié à l’eau d’irrigation', 'risk'],
    ['machine', 'Utilisation non maîtrisée d’un matériel agricole', 'training'],
    ['delivery', 'Retard de collecte ou d’approvisionnement', 'delay'],
    ['chemical', 'Exposition à un produit phytosanitaire', 'accident'],
  ],
  animals: [
    ['feed', 'Aliment pour animaux non conforme', 'conformity'],
    ['care', 'Erreur de soin ou de suivi des animaux', 'conformity'],
    ['health', 'Risque sanitaire dans l’élevage', 'risk'],
    ['trace', 'Identification ou traçabilité des animaux incomplète', 'document'],
    ['hygiene', 'Consigne d’hygiène des installations non respectée', 'procedure'],
    ['transport', 'Incident lors du transport des animaux', 'conformity'],
    ['supplies', 'Fourniture vétérinaire ou agricole non conforme', 'supplier'],
    ['staff', 'Personnel non formé à la manipulation des animaux', 'training'],
  ],
  food: [
    ['expiry', 'Produit périmé, expiré ou DLC dépassée', 'food'],
    ['cold', 'Rupture de la chaîne du froid', 'food'],
    ['contamination', 'Contamination ou suspicion de contamination alimentaire', 'food'],
    ['allergen', 'Allergène non déclaré ou erreur d’étiquetage', 'food'],
    ['hygiene', 'Nettoyage ou désinfection non conforme', 'food'],
    ['cooking', 'Cuisson, refroidissement ou température non maîtrisés', 'food'],
    ['trace', 'Traçabilité d’un lot alimentaire incomplète', 'document'],
    ['receipt', 'Produit alimentaire non conforme à réception', 'supplier'],
    ['foreign', 'Corps étranger dans un produit alimentaire', 'food'],
    ['ccp', 'Écart constaté lors d’un contrôle HACCP', 'food'],
  ],
  construction: [
    ['work', 'Travaux ou ouvrage non conformes', 'conformity'],
    ['plans', 'Plan de chantier obsolète ou non validé', 'document'],
    ['materials', 'Matériaux non conformes à réception', 'supplier'],
    ['height', 'Chute ou incident lors d’un travail en hauteur', 'accident'],
    ['deadline', 'Retard de chantier ou de réception des travaux', 'delay'],
    ['handover', 'Réserve ou défaut constaté à la réception', 'conformity'],
    ['subcontract', 'Prestation d’un sous-traitant non conforme', 'supplier'],
    ['ppe', 'Consigne de sécurité ou port des EPI non respecté', 'procedure'],
    ['skills', 'Habilitation ou compétence nécessaire non acquise', 'training'],
  ],
  industry: [
    ['dimension', 'Dimension, tolérance ou assemblage non conforme', 'conformity'],
    ['scrap', 'Hausse des rebuts ou des retouches', 'measurement'],
    ['machine', 'Panne récurrente d’un équipement de production', 'recurring'],
    ['setting', 'Erreur de réglage ou de paramétrage machine', 'conformity'],
    ['material', 'Matière première ou composant non conforme', 'supplier'],
    ['batch', 'Traçabilité de fabrication ou de lot incomplète', 'document'],
    ['inspection', 'Contrôle de production non effectué ou non enregistré', 'procedure'],
    ['safety', 'Incident de sécurité sur une machine', 'accident'],
    ['qualification', 'Personnel non formé à une opération de production', 'training'],
  ],
  chemical: [
    ['dose', 'Dosage, formulation ou mélange non conforme', 'conformity'],
    ['leak', 'Fuite ou déversement de produit dangereux', 'risk'],
    ['exposure', 'Exposition d’un salarié à un produit dangereux', 'accident'],
    ['label', 'Étiquetage ou fiche de sécurité incorrects', 'document'],
    ['storage', 'Stockage de produits incompatibles', 'risk'],
    ['batch', 'Lot ou matière première hors spécification', 'conformity'],
    ['procedure', 'Consigne de manipulation chimique non respectée', 'procedure'],
    ['trace', 'Dossier de fabrication ou traçabilité incomplet', 'document'],
  ],
  transport: [
    ['delivery', 'Livraison tardive ou délai de transport dépassé', 'delay'],
    ['damage', 'Marchandise endommagée pendant le transport', 'conformity'],
    ['destination', 'Erreur de destinataire ou d’adresse de livraison', 'conformity'],
    ['loss', 'Colis ou marchandise perdu', 'conformity'],
    ['accident', 'Accident lors d’une opération de transport', 'accident'],
    ['carrier', 'Transporteur ou sous-traitant non satisfaisant', 'supplier'],
    ['documents', 'Document de transport absent ou incorrect', 'document'],
    ['route', 'Planification des tournées ou des moyens insuffisante', 'improvement'],
    ['training', 'Conducteur non formé à une consigne de transport', 'training'],
  ],
  logistics: [
    ['picking', 'Erreur de préparation de commande', 'conformity'],
    ['stock', 'Écart entre le stock physique et le stock enregistré', 'conformity'],
    ['storage', 'Marchandise mal stockée ou détériorée', 'conformity'],
    ['label', 'Erreur d’identification, d’étiquetage ou de lot', 'conformity'],
    ['receipt', 'Marchandise non conforme à réception', 'supplier'],
    ['dispatch', 'Retard de préparation ou d’expédition', 'delay'],
    ['trace', 'Traçabilité d’un mouvement ou d’un lot manquante', 'document'],
    ['handling', 'Accident de manutention ou de circulation en entrepôt', 'accident'],
    ['recurrence', 'Erreurs de préparation récurrentes', 'recurring'],
  ],
  retail: [
    ['order', 'Erreur de commande ou article incorrect remis au client', 'conformity'],
    ['return', 'Retour client pour un produit défectueux', 'complaint'],
    ['display', 'Information produit ou étiquetage incorrect', 'conformity'],
    ['stock', 'Rupture de stock ou disponibilité non respectée', 'conformity'],
    ['refund', 'Réclamation concernant un échange ou un remboursement', 'complaint'],
    ['supplier', 'Produits défectueux livrés par un fournisseur', 'supplier'],
    ['preparation', 'Erreur de préparation d’une commande en ligne', 'conformity'],
    ['delivery', 'Délai de livraison annoncé non respecté', 'delay'],
  ],
  health: [
    ['identity', 'Erreur d’identification d’un patient ou d’un dossier', 'conformity'],
    ['care', 'Écart dans la réalisation d’un soin ou d’un accompagnement', 'conformity'],
    ['hygiene', 'Protocole d’hygiène non respecté', 'procedure'],
    ['device', 'Dispositif médical ou matériel non conforme', 'conformity'],
    ['expiry', 'Produit de soin ou médicament périmé', 'conformity'],
    ['record', 'Dossier patient ou traçabilité de soin incomplets', 'document'],
    ['complaint', 'Réclamation d’un patient, résident ou proche', 'complaint'],
    ['risk', 'Risque identifié pour la sécurité des personnes', 'risk'],
    ['exposure', 'Accident d’exposition d’un professionnel', 'accident'],
    ['skills', 'Compétence ou formation professionnelle à actualiser', 'training'],
  ],
  laboratory: [
    ['sample', 'Échantillon mal identifié ou non conforme', 'conformity'],
    ['result', 'Résultat d’analyse incohérent ou hors spécification', 'conformity'],
    ['method', 'Méthode ou protocole d’analyse non respecté', 'procedure'],
    ['reagent', 'Réactif périmé ou non conforme', 'conformity'],
    ['trace', 'Traçabilité des analyses ou des échantillons incomplète', 'document'],
    ['delay', 'Retard de remise d’un résultat d’analyse', 'delay'],
    ['equipment', 'Écart constaté sur un équipement de mesure', 'conformity'],
    ['exposure', 'Exposition à un agent biologique ou chimique', 'accident'],
  ],
  technology: [
    ['bug', 'Anomalie logicielle ou fonctionnalité non conforme', 'conformity'],
    ['outage', 'Indisponibilité d’un service informatique', 'conformity'],
    ['recurring', 'Incident informatique récurrent', 'recurring'],
    ['data', 'Risque de perte de données ou de confidentialité', 'risk'],
    ['deployment', 'Erreur de déploiement ou de configuration', 'conformity'],
    ['sla', 'Engagement de service ou délai de résolution non respecté', 'delay'],
    ['documentation', 'Documentation technique absente ou obsolète', 'document'],
    ['change', 'Procédure de changement non respectée', 'procedure'],
    ['provider', 'Prestataire informatique non satisfaisant', 'supplier'],
  ],
  education: [
    ['training', 'Contenu pédagogique ou formation non conforme', 'conformity'],
    ['learner', 'Réclamation d’un apprenant ou d’une famille', 'complaint'],
    ['attendance', 'Justificatif de présence ou de réalisation manquant', 'document'],
    ['assessment', 'Erreur d’évaluation ou de certification', 'conformity'],
    ['skills', 'Formateur ou intervenant insuffisamment qualifié', 'training'],
    ['schedule', 'Retard ou annulation d’une session', 'delay'],
    ['access', 'Risque lié à l’accueil ou à l’accessibilité', 'risk'],
    ['outcome', 'Résultats pédagogiques ou satisfaction en baisse', 'measurement'],
  ],
  hospitality: [
    ['room', 'Chambre, logement ou espace d’accueil non conforme', 'conformity'],
    ['booking', 'Erreur de réservation ou de prise en charge', 'conformity'],
    ['cleaning', 'Prestation de nettoyage insuffisante', 'conformity'],
    ['guest', 'Réclamation d’un visiteur ou d’un client hébergé', 'complaint'],
    ['delay', 'Retard dans la préparation ou la remise d’une prestation', 'delay'],
    ['equipment', 'Équipement fourni au client défectueux', 'conformity'],
    ['safety', 'Risque lié à l’accueil du public', 'risk'],
    ['staff', 'Personnel non formé aux standards d’accueil', 'training'],
  ],
  environment: [
    ['sorting', 'Erreur de tri ou de traitement des déchets', 'conformity'],
    ['spill', 'Pollution, fuite ou déversement accidentel', 'risk'],
    ['water', 'Résultat de contrôle de l’eau non conforme', 'conformity'],
    ['trace', 'Traçabilité des déchets ou des opérations incomplète', 'document'],
    ['collection', 'Retard ou absence de collecte', 'delay'],
    ['ppe', 'Consigne de protection ou de sécurité non respectée', 'procedure'],
    ['exposure', 'Exposition d’un salarié à un risque environnemental', 'accident'],
    ['provider', 'Prestataire de traitement non satisfaisant', 'supplier'],
  ],
  energy: [
    ['supply', 'Interruption ou défaut de fourniture d’énergie', 'conformity'],
    ['equipment', 'Installation ou équipement non conforme', 'conformity'],
    ['electrical', 'Risque électrique ou lié à une installation', 'risk'],
    ['accident', 'Accident lors d’une intervention sur une installation', 'accident'],
    ['maintenance', 'Intervention de maintenance en retard', 'delay'],
    ['procedure', 'Consigne d’exploitation ou de consignation non respectée', 'procedure'],
    ['skills', 'Habilitation ou formation technique insuffisante', 'training'],
    ['trace', 'Rapport d’intervention ou contrôle manquant', 'document'],
  ],
  finance: [
    ['file', 'Dossier client incomplet ou incorrect', 'conformity'],
    ['calculation', 'Erreur de calcul, de facturation ou de traitement', 'conformity'],
    ['deadline', 'Délai de traitement d’un dossier dépassé', 'delay'],
    ['privacy', 'Risque de confidentialité ou de protection des données', 'risk'],
    ['claim', 'Réclamation concernant une décision ou une prestation', 'complaint'],
    ['procedure', 'Procédure de vérification non respectée', 'procedure'],
    ['trace', 'Justificatif ou preuve de contrôle manquants', 'document'],
    ['recurrence', 'Erreurs récurrentes de traitement administratif', 'recurring'],
  ],
  services: [
    ['deliverable', 'Livrable ou prestation ne répondant pas au besoin', 'conformity'],
    ['delay', 'Délai de réponse ou de réalisation dépassé', 'delay'],
    ['file', 'Erreur de saisie ou de traitement d’un dossier', 'conformity'],
    ['handover', 'Information mal transmise entre intervenants', 'conformity'],
    ['scope', 'Besoin client ou périmètre de prestation mal défini', 'complaint'],
    ['privacy', 'Risque lié à la confidentialité des informations', 'risk'],
    ['provider', 'Intervenant ou prestataire externe non satisfaisant', 'supplier'],
    ['capacity', 'Organisation de la charge de travail à améliorer', 'improvement'],
  ],
  security: [
    ['access', 'Consigne de contrôle d’accès non respectée', 'procedure'],
    ['patrol', 'Ronde ou contrôle prévu non réalisé', 'conformity'],
    ['incident', 'Incident mal signalé ou rapport incomplet', 'document'],
    ['equipment', 'Équipement de sécurité défectueux', 'conformity'],
    ['response', 'Délai d’intervention non respecté', 'delay'],
    ['skills', 'Agent non formé à une mission ou une consigne', 'training'],
    ['violence', 'Agression ou accident subi par un agent', 'accident'],
    ['risk', 'Risque identifié sur un site surveillé', 'risk'],
  ],
};

const SECTORS = [
  ['agriculture', 'Agriculture et cultures', ['agriculture']],
  ['food-industry', 'Agroalimentaire', ['industry', 'food']],
  ['airport', 'Aéroports et services aéroportuaires', ['transport', 'services']],
  ['craft', 'Artisanat', ['industry', 'services']],
  ['insurance', 'Assurances', ['finance']],
  ['automotive', 'Automobile et équipementiers', ['industry']],
  ['aviation', 'Aéronautique et spatial', ['industry', 'transport']],
  ['banking', 'Banque et services financiers', ['finance']],
  ['construction', 'Bâtiment et construction', ['construction']],
  ['beauty', 'Beauté, coiffure et bien-être', ['services', 'chemical']],
  ['bakery', 'Boulangerie et pâtisserie', ['food']],
  ['butchery', 'Boucherie et charcuterie', ['food']],
  ['wood', 'Bois, ameublement et menuiserie', ['industry']],
  ['chemical', 'Chimie et pétrochimie', ['industry', 'chemical']],
  ['retail', 'Commerce de détail', ['retail']],
  ['wholesale', 'Commerce de gros et distribution', ['retail', 'logistics']],
  ['consulting', 'Conseil et bureaux d’études', ['services']],
  ['accounting', 'Comptabilité et gestion', ['finance']],
  ['cosmetics', 'Cosmétique et parfumerie', ['industry', 'chemical']],
  ['culture', 'Culture, loisirs et spectacles', ['hospitality', 'services']],
  ['home-care', 'Aide à domicile et services à la personne', ['health', 'services']],
  ['waste', 'Déchets, recyclage et valorisation', ['environment']],
  ['medical-devices', 'Dispositifs médicaux', ['industry', 'health']],
  ['water', 'Eau et assainissement', ['environment', 'energy']],
  ['publishing', 'Édition, imprimerie et packaging', ['industry']],
  ['breeding', 'Élevage et activités vétérinaires', ['animals']],
  ['electronics', 'Électronique et équipements électriques', ['industry', 'energy']],
  ['energy', 'Énergie et énergies renouvelables', ['energy']],
  ['education', 'Enseignement et formation', ['education']],
  ['storage', 'Entreposage et plateformes logistiques', ['logistics']],
  ['events', 'Événementiel', ['hospitality', 'services']],
  ['railway', 'Ferroviaire', ['transport', 'industry']],
  ['forest', 'Foresterie et exploitation forestière', ['agriculture', 'industry']],
  ['hotel', 'Hôtellerie et hébergement', ['hospitality']],
  ['real-estate', 'Immobilier et gestion de bâtiments', ['construction', 'services']],
  ['mechanical', 'Industrie mécanique et métallurgie', ['industry']],
  ['mining', 'Industries extractives et carrières', ['industry', 'environment']],
  ['it', 'Informatique, logiciels et services numériques', ['technology']],
  ['laboratory', 'Laboratoires d’analyses et d’essais', ['laboratory']],
  ['logistics', 'Logistique et chaîne d’approvisionnement', ['logistics', 'transport']],
  ['maintenance', 'Maintenance et réparation', ['industry', 'services']],
  ['marine', 'Maritime et activités portuaires', ['transport', 'logistics']],
  ['medical-social', 'Médico-social et établissements d’accueil', ['health', 'hospitality']],
  ['cleaning', 'Nettoyage et propreté', ['services', 'chemical']],
  ['fishing', 'Pêche et aquaculture', ['animals', 'food']],
  ['pharma', 'Pharmacie et industrie pharmaceutique', ['chemical', 'health', 'laboratory']],
  ['plastics', 'Plasturgie et caoutchouc', ['industry', 'chemical']],
  ['public', 'Administration et services publics', ['services', 'finance']],
  ['research', 'Recherche et développement', ['laboratory', 'technology']],
  ['restaurants', 'Restauration et métiers de bouche', ['food', 'hospitality']],
  ['collective-catering', 'Restauration collective', ['food']],
  ['health', 'Santé et établissements de soins', ['health']],
  ['security', 'Sécurité privée et gardiennage', ['security']],
  ['business-services', 'Services aux entreprises', ['services']],
  ['sport', 'Sport et équipements de loisirs', ['hospitality', 'services']],
  ['telecom', 'Télécommunications', ['technology', 'energy']],
  ['textile', 'Textile, habillement et cuir', ['industry', 'retail']],
  ['tourism', 'Tourisme et agences de voyages', ['hospitality', 'transport']],
  ['road-transport', 'Transport routier de marchandises', ['transport', 'logistics']],
  ['passenger-transport', 'Transport de personnes', ['transport', 'hospitality']],
  ['civil-engineering', 'Travaux publics et génie civil', ['construction']],
  ['general', 'Activités transversales et autres secteurs', ['services']],
];

export const PROBLEM_SECTORS = SECTORS.map(([id, label, profiles]) => ({ id, label, profiles })).sort(compareLabels);

export function getSectorProblems(sectorId) {
  const sector = PROBLEM_SECTORS.find(({ id }) => id === sectorId);
  if (!sector) return [];
  const toProblem = (namespace) => ([id, label, pathway, facts]) => ({
    id: `${namespace}:${id}`, label, pathway, ...(facts ? { facts } : {}),
  });
  const common = [...COMMON_PROBLEMS, ...COMMON_SITUATIONS].map(toProblem('common'));
  const specific = sector.profiles.flatMap((profile) =>
    [...SECTOR_PROFILES[profile], ...PROFILE_SITUATIONS[profile]].map(toProblem(profile)));
  const sectorSpecific = SECTOR_SITUATIONS[sector.id].map(toProblem(`sector.${sector.id}`));
  return [...common, ...specific, ...sectorSpecific].sort(compareLabels);
}

export function getSectorRecommendations(sectorId, problemId, access) {
  const problem = getSectorProblems(sectorId).find(({ id }) => id === problemId);
  if (!problem) return [];
  const available = new Map(getAvailableProblemModules(access).map((module) => [module.id, module]));
  return MODULE_PATHWAYS[problem.pathway].flatMap((id, index) => {
    const module = available.get(id);
    return module ? [{ ...module, score: [120, 95, 80, 65][index] }] : [];
  });
}
