// Each situation keeps its specific evidence beside its module pathway.
export const COMMON_SITUATIONS = [
  ['handover', 'Passation de poste ou transmission incomplète', 'conformity', 'les informations attendues, les équipes concernées et les éléments omis lors de la passation'],
  ['approval', 'Validation réalisée sans autorisation ou preuve', 'procedure', 'la décision prise, les règles de validation et les autorisations ou preuves absentes'],
  ['change', 'Changement de processus non évalué', 'risk', 'le changement prévu, les activités affectées et les évaluations réalisées avant sa mise en œuvre'],
  ['continuity', 'Plan de continuité absent ou non testé', 'risk', 'les activités critiques, les interruptions envisagées et les résultats des exercices disponibles'],
  ['ownership', 'Responsabilités ou délégations mal définies', 'improvement', 'les tâches concernées, les responsables actuels et les décisions sans attribution claire'],
  ['overload', 'Surcharge de travail et moyens insuffisants', 'improvement', 'la charge prévue, les moyens disponibles, les priorités et les activités en attente'],
  ['absence', 'Absence imprévue sur un poste critique', 'delay', 'le poste, les activités à couvrir, les compétences nécessaires et les échéances affectées'],
  ['conflict', 'Consignes contradictoires entre services', 'document', 'les consignes en conflit, leurs versions et les opérations pour lesquelles elles divergent'],
  ['calibration', 'Étalonnage ou vérification périodique dépassés', 'conformity', 'les équipements concernés, les échéances de vérification et les mesures réalisées depuis le dépassement'],
  ['maintenance', 'Maintenance préventive non réalisée', 'delay', 'les équipements, les interventions prévues, les échéances dépassées et les conséquences constatées'],
  ['archive', 'Preuve ou enregistrement introuvable', 'document', 'la preuve recherchée, la période, les lieux de conservation et les recherches déjà réalisées'],
  ['reporting', 'Données de suivi incomplètes ou incohérentes', 'measurement', 'les sources, la période, les champs manquants et les écarts entre les données comparées'],
  ['effectiveness', 'Efficacité d’une action non vérifiée', 'corrective', 'l’action engagée, l’objectif prévu, l’échéance et les preuves nécessaires à sa vérification'],
  ['objective', 'Objectif qualité non atteint', 'measurement', 'l’objectif, la période, le résultat mesuré et les facteurs de variation observés'],
  ['emergency', 'Exercice d’urgence non réalisé ou non concluant', 'risk', 'le scénario, les participants, les écarts observés et les consignes internes à revoir'],
  ['feedback', 'Retours des utilisateurs non pris en compte', 'complaint', 'les retours reçus, les engagements de réponse et les besoins restés sans traitement'],
];

export const PROFILE_SITUATIONS = {
  agriculture: [
    ['seed', 'Semences ou plants de qualité insuffisante', 'supplier', 'la variété, le fournisseur, le lot et les taux de levée ou défauts observés'],
    ['soil', 'Analyse de sol manquante ou résultat défavorable', 'conformity', 'la parcelle, la date de prélèvement, les résultats et les références agronomiques internes'],
    ['irrigation', 'Panne ou dérive du système d’irrigation', 'conformity', 'les zones irriguées, les débits observés, les horaires et les équipements concernés'],
    ['weather', 'Dégâts liés au gel, à la grêle ou à la sécheresse', 'risk', 'les parcelles exposées, les dates des événements et les pertes ou dégâts constatés'],
    ['pests', 'Présence de ravageurs ou de maladie sur les cultures', 'risk', 'la culture, les zones touchées, les observations et les signalements au référent compétent'],
    ['residue', 'Résidus ou contaminant détectés dans une récolte', 'conformity', 'le lot, le prélèvement, le rapport de contrôle et les exigences applicables'],
    ['rotation', 'Rotation ou calendrier cultural non respectés', 'procedure', 'le calendrier prévu, les cultures successives et les écarts de réalisation'],
    ['fertilizer', 'Épandage ou fertilisation mal enregistrés', 'document', 'les parcelles, les dates, les quantités enregistrées et les justificatifs manquants'],
    ['erosion', 'Érosion ou dégradation observée d’une parcelle', 'risk', 'les zones concernées, les événements précédents et les observations de terrain'],
    ['fuel', 'Fuite de carburant sur une exploitation', 'risk', 'le lieu, le matériel et les observations transmises selon le dispositif interne d’alerte'],
    ['harvest-storage', 'Récolte détériorée pendant le stockage', 'conformity', 'le silo ou local, le lot, les conditions enregistrées et les pertes constatées'],
    ['yield-record', 'Pesée ou déclaration de récolte incorrecte', 'conformity', 'les pesées, les lots, les documents de déclaration et les écarts de quantité'],
    ['seasonal', 'Accueil ou formation des saisonniers incomplets', 'training', 'les postes saisonniers, les consignes nécessaires et les formations non réalisées'],
    ['certification', 'Exigence de certification agricole non démontrée', 'audit', 'le référentiel, le point contrôlé et les preuves disponibles pour la parcelle ou le lot'],
    ['neighbors', 'Réclamation de riverains concernant l’exploitation', 'complaint', 'la nuisance signalée, la période, la zone et les échanges déjà réalisés'],
  ],
  animals: [
    ['welfare', 'Écart aux conditions de bien-être animal', 'risk', 'les observations, les installations, les conditions d’accueil et les exigences internes'],
    ['water', 'Abreuvement insuffisant ou équipement défectueux', 'conformity', 'les installations, les contrôles d’eau disponibles et les dysfonctionnements observés'],
    ['ventilation', 'Ventilation ou température d’élevage non maîtrisées', 'risk', 'les bâtiments, les températures enregistrées et les alarmes ou pannes constatées'],
    ['mortality', 'Hausse inhabituelle de mortalité dans un élevage', 'measurement', 'la période, les effectifs concernés et les observations transmises au professionnel compétent'],
    ['isolation', 'Consigne de séparation des animaux non respectée', 'procedure', 'la consigne applicable, les mouvements d’animaux et les écarts observés'],
    ['medicine', 'Stock ou registre de produits vétérinaires incorrect', 'document', 'les références, les lots, les dates et les mouvements absents du registre'],
    ['withdrawal', 'Délai d’attente vétérinaire mal enregistré', 'conformity', 'le traitement prescrit, les dates enregistrées et les lots de production concernés'],
    ['reproduction', 'Suivi de reproduction incomplet', 'document', 'les identifiants des animaux, les dates et les événements manquants du suivi'],
    ['escape', 'Animal échappé ou clôture défectueuse', 'risk', 'la zone, les équipements concernés et les circonstances signalées au responsable'],
    ['bite', 'Morsure ou blessure lors d’une manipulation animale', 'accident', 'le lieu, la tâche et les circonstances, selon les consignes internes de déclaration'],
    ['ration', 'Erreur dans la préparation d’une ration', 'conformity', 'la ration prévue, les ingrédients, les quantités et les groupes concernés'],
    ['bedding', 'Litière ou logement animal non conforme', 'conformity', 'les zones, les critères attendus et les défauts constatés lors du contrôle'],
    ['movement', 'Mouvement d’animaux déclaré tardivement', 'delay', 'les identifiants, la date de mouvement, l’échéance et la déclaration effectuée'],
    ['biosecurity', 'Contrôle des entrées en élevage insuffisant', 'procedure', 'les accès, les consignes sanitaires et les enregistrements de visiteurs disponibles'],
    ['veterinary', 'Retard de prestation vétérinaire prévue', 'supplier', 'la prestation commandée, le délai convenu et les échanges avec le prestataire'],
  ],
  food: [
    ['packaging', 'Emballage alimentaire endommagé ou non étanche', 'food', 'le lot, le type d’emballage, les défauts observés et les contrôles d’intégrité'],
    ['date-label', 'Date limite ou numéro de lot erronés sur l’étiquette', 'food', 'la date attendue, la date imprimée, le lot et les quantités étiquetées'],
    ['recipe', 'Erreur de recette, d’ingrédient ou de dosage alimentaire', 'food', 'la recette validée, les ingrédients utilisés, les quantités et le lot préparé'],
    ['thawing', 'Décongélation non conforme aux consignes', 'food', 'les produits, les horaires, les températures enregistrées et la consigne applicable'],
    ['reheating', 'Remise en température non maîtrisée', 'food', 'les lots, les horaires et les températures mesurées lors de la remise en température'],
    ['holding', 'Maintien au chaud non conforme', 'food', 'les préparations, les températures relevées et la durée du maintien au chaud'],
    ['cross-contact', 'Contact croisé entre produits crus et prêts à consommer', 'food', 'les produits concernés, les postes, les ustensiles et les circonstances observées'],
    ['pests', 'Présence de nuisibles dans une zone alimentaire', 'food', 'la zone, les observations, les produits potentiellement concernés et les contrôles disponibles'],
    ['oil', 'Huile de cuisson ou de friture non conforme', 'food', 'l’équipement, les contrôles enregistrés, les dates d’utilisation et les préparations concernées'],
    ['water', 'Eau utilisée en préparation alimentaire non conforme', 'food', 'le point d’eau, les usages, les résultats de contrôle et les lots préparés'],
    ['recall', 'Traçabilité insuffisante pour un retrait ou rappel alimentaire', 'food', 'les lots visés, les quantités, les destinataires et les preuves de retrait disponibles'],
    ['sample', 'Échantillon témoin ou prélèvement alimentaire manquant', 'procedure', 'les préparations, les dates et les prélèvements exigés par les consignes internes'],
    ['delivery-temp', 'Température de livraison alimentaire hors limite', 'food', 'le transport, les températures à réception, les lots et les horaires de livraison'],
    ['waste', 'Gaspillage ou pertes alimentaires en hausse', 'measurement', 'les quantités préparées, servies et perdues, les motifs et la période comparée'],
    ['portion', 'Portion ou poids alimentaire non conforme', 'conformity', 'le poids attendu, les contrôles de portion, le lot et les quantités concernées'],
  ],
  construction: [
    ['foundation', 'Défaut de fondation ou de terrassement', 'conformity', 'la zone, les plans validés, les contrôles et les écarts de réalisation'],
    ['concrete', 'Bétonnage ou résultat de contrôle béton non conforme', 'conformity', 'le lot de béton, la zone coulée, les conditions enregistrées et les résultats d’essais'],
    ['waterproofing', 'Défaut d’étanchéité ou infiltration sur un ouvrage', 'conformity', 'la localisation, les conditions d’apparition et les contrôles d’étanchéité disponibles'],
    ['scaffold', 'Échafaudage ou protection collective non conformes', 'risk', 'la zone de travail, les vérifications disponibles et les anomalies signalées'],
    ['excavation', 'Risque identifié autour d’une fouille ou tranchée', 'risk', 'la zone, les travaux en cours et les protections prévues selon les consignes du chantier'],
    ['network', 'Réseau enterré non identifié avant intervention', 'risk', 'les plans disponibles, les repérages et la zone d’intervention prévue'],
    ['lifting', 'Incident ou défaut lors d’une opération de levage', 'accident', 'l’équipement, la charge et les circonstances transmises selon le dispositif du chantier'],
    ['coactivity', 'Coordination insuffisante entre entreprises sur chantier', 'risk', 'les entreprises, les tâches simultanées, les zones et les consignes de coordination'],
    ['permit', 'Autorisation de travaux ou permis interne manquants', 'document', 'les travaux prévus, les autorisations exigées et les validations absentes'],
    ['measurement', 'Erreur d’implantation ou de relevé topographique', 'conformity', 'les références, les relevés, les équipements et les points d’implantation concernés'],
    ['finish', 'Défaut de finition ou de pose sur chantier', 'conformity', 'les surfaces ou équipements, les critères attendus et les défauts relevés'],
    ['asbestos', 'Matériau potentiellement dangereux non signalé', 'risk', 'la zone, les repérages disponibles et le signalement au personnel compétent, sans manipulation improvisée'],
    ['noise', 'Réclamation liée aux nuisances du chantier', 'complaint', 'la nuisance signalée, les horaires, les travaux concernés et les engagements pris'],
    ['waste', 'Tri ou évacuation des déchets de chantier non conformes', 'procedure', 'les déchets, les zones de stockage, les consignes et les preuves d’évacuation'],
    ['handover-file', 'Dossier de fin de travaux incomplet', 'document', 'les pièces attendues, les lots de travaux et les documents manquants à la remise'],
  ],
  industry: [
    ['surface', 'Défaut d’aspect ou de traitement de surface', 'conformity', 'la pièce, le lot, le traitement attendu et les défauts relevés'],
    ['weld', 'Soudure ou liaison mécanique non conforme', 'conformity', 'les assemblages, les exigences, les contrôles disponibles et les zones en écart'],
    ['tool', 'Outil usé, cassé ou inadapté à la fabrication', 'conformity', 'l’outil, les opérations, les contrôles d’usure et les pièces produites'],
    ['program', 'Programme de fabrication incorrect ou mauvaise version', 'document', 'la référence du programme, sa version validée et les lots fabriqués avec chaque version'],
    ['mix-up', 'Mélange de références ou de lots en production', 'conformity', 'les références, les lots, les postes et les quantités potentiellement mélangées'],
    ['startup', 'Validation de démarrage de série non réalisée', 'procedure', 'la série, les contrôles de première pièce et les validations attendues'],
    ['stop', 'Arrêt imprévu de ligne de production', 'delay', 'la ligne, la durée d’arrêt, les commandes affectées et les ressources disponibles'],
    ['capacity', 'Capacité de production insuffisante', 'improvement', 'les volumes attendus, les capacités par poste et les goulots observés'],
    ['packaging', 'Conditionnement industriel non conforme', 'conformity', 'la référence, les exigences d’emballage et les défauts ou dommages constatés'],
    ['release', 'Lot libéré sans contrôle ou validation requis', 'procedure', 'le lot, les résultats disponibles et les étapes de libération non démontrées'],
    ['metrology', 'Instrument de mesure défectueux ou hors tolérance', 'conformity', 'l’instrument, les contrôles, la période d’utilisation et les mesures concernées'],
    ['utility', 'Défaut d’air comprimé ou d’utilité de production', 'conformity', 'le réseau, les paramètres enregistrés et les opérations perturbées'],
    ['guard', 'Protection de machine absente ou neutralisée', 'risk', 'la machine, les protections attendues et le constat signalé au responsable compétent'],
    ['energy', 'Consommation de production anormalement élevée', 'measurement', 'les consommations, les volumes produits, les périodes et les équipements comparés'],
    ['rework', 'Retouche non validée ou non tracée', 'procedure', 'les pièces retouchées, la méthode autorisée et les contrôles après retouche'],
  ],
  chemical: [
    ['reaction', 'Dérive des paramètres d’une réaction ou formulation', 'conformity', 'le lot, les paramètres attendus et les valeurs enregistrées dans le dossier de fabrication'],
    ['purity', 'Pureté ou concentration hors spécification', 'conformity', 'les résultats, la méthode de contrôle, le lot et les limites de spécification'],
    ['stability', 'Stabilité d’un produit non démontrée', 'conformity', 'les lots, les conditions d’étude et les résultats de stabilité disponibles'],
    ['container', 'Contenant chimique endommagé ou inadapté', 'risk', 'le produit, le contenant, les défauts et les exigences de compatibilité applicables'],
    ['transfer', 'Erreur de transfert de produit entre cuves', 'conformity', 'les cuves, les références, les quantités et les enregistrements de transfert'],
    ['contamination', 'Contamination croisée entre fabrications chimiques', 'conformity', 'les fabrications successives, les équipements partagés et les contrôles disponibles'],
    ['cleaning', 'Validation de nettoyage d’un équipement insuffisante', 'procedure', 'l’équipement, le protocole, les prélèvements et les preuves de validation'],
    ['retention', 'Dispositif de rétention absent ou défectueux', 'risk', 'la zone de stockage, les contenants et les contrôles du dispositif de rétention'],
    ['ventilation', 'Ventilation d’une zone chimique insuffisante', 'risk', 'la zone, les contrôles de ventilation et les défauts signalés selon les consignes internes'],
    ['expiry', 'Produit chimique périmé ou durée de conservation dépassée', 'conformity', 'la référence, le lot, la date limite et les usages réalisés depuis le dépassement'],
    ['sample', 'Prélèvement de fabrication chimique incorrect', 'conformity', 'le lot, le point de prélèvement, la méthode et les conditions enregistrées'],
    ['emission', 'Rejet ou émission chimique hors limite interne', 'risk', 'le point de rejet, les mesures, les limites applicables et les signalements effectués'],
    ['inventory', 'Inventaire de produits dangereux incomplet', 'document', 'les produits présents, les quantités, les emplacements et les références absentes de l’inventaire'],
    ['transport-label', 'Marquage de transport d’un produit dangereux incorrect', 'document', 'le produit, l’expédition et les documents ou marquages vérifiés par les personnes habilitées'],
    ['supplier-change', 'Changement de matière chimique non qualifié', 'supplier', 'la matière, le fournisseur, les spécifications et les validations du changement'],
  ],
  transport: [
    ['loading', 'Chargement ou arrimage non conforme', 'risk', 'le véhicule, le chargement et les contrôles ou écarts signalés au personnel compétent'],
    ['overload', 'Charge ou répartition de poids non conforme', 'conformity', 'les poids enregistrés, le véhicule et les exigences de chargement applicables'],
    ['vehicle', 'Véhicule indisponible ou panne en tournée', 'delay', 'le véhicule, le trajet, la durée d’immobilisation et les livraisons affectées'],
    ['maintenance', 'Contrôle ou entretien de véhicule non réalisé', 'procedure', 'le véhicule, les opérations prévues et les échéances ou contrôles manquants'],
    ['customs', 'Blocage d’expédition lié à un dossier douanier', 'delay', 'l’expédition, les justificatifs demandés, les délais et les échanges avec les intervenants'],
    ['seal', 'Scellé absent, rompu ou non concordant', 'conformity', 'l’expédition, les numéros de scellé, les contrôles et les circonstances du constat'],
    ['proof', 'Preuve de livraison absente ou contestée', 'document', 'la livraison, l’heure, les documents remis et les éléments de preuve disponibles'],
    ['passenger', 'Information voyageur incorrecte ou non transmise', 'conformity', 'le service, le message attendu, les canaux utilisés et les voyageurs affectés'],
    ['accessibility', 'Prise en charge d’un voyageur à besoins spécifiques non assurée', 'conformity', 'la demande de prise en charge, le service prévu et les écarts sans donnée personnelle inutile'],
    ['fatigue', 'Risque lié à la fatigue ou aux temps de conduite', 'risk', 'les horaires, l’organisation du trajet et les signalements selon les consignes applicables'],
    ['theft', 'Vol ou tentative de vol pendant un transport', 'risk', 'le trajet, les marchandises concernées et les éléments signalés aux responsables compétents'],
    ['tracking', 'Suivi de transport absent ou position incohérente', 'conformity', 'l’expédition, les événements attendus et les écarts dans les informations de suivi'],
    ['booking', 'Capacité ou créneau de transport mal réservé', 'conformity', 'la réservation, les moyens attendus et les confirmations reçues'],
    ['fuel', 'Consommation de carburant anormale sur un trajet', 'measurement', 'les trajets comparés, les distances, les charges et les consommations enregistrées'],
    ['hazardous', 'Consigne de transport de matières dangereuses non respectée', 'procedure', 'l’expédition, les consignes applicables et les contrôles réalisés par les personnes habilitées'],
  ],
  logistics: [
    ['fifo', 'Rotation des stocks ou priorité de sortie non respectées', 'procedure', 'les lots, les dates d’entrée, les priorités prévues et les mouvements réalisés'],
    ['location', 'Emplacement de stockage incorrect ou introuvable', 'conformity', 'la référence, l’emplacement attendu et les recherches ou mouvements enregistrés'],
    ['pallet', 'Palette ou support de manutention endommagé', 'conformity', 'le support, la marchandise, les défauts et les contrôles à réception'],
    ['rack', 'Rayonnage endommagé ou charge non conforme', 'risk', 'la zone, le rayonnage et les dommages ou écarts signalés au responsable'],
    ['dock', 'Incident ou risque lors d’une opération à quai', 'risk', 'le quai, les équipements et les circonstances selon le dispositif interne d’alerte'],
    ['scan', 'Code-barres illisible ou erreur de lecture', 'conformity', 'les références, les étiquettes, les lecteurs et les opérations affectées'],
    ['quantity', 'Quantité expédiée différente de la commande', 'conformity', 'la commande, les quantités préparées, contrôlées et reçues par le destinataire'],
    ['replenishment', 'Réapprovisionnement d’un emplacement non réalisé', 'delay', 'l’emplacement, les besoins prévus, le stock disponible et les délais de réapprovisionnement'],
    ['returns', 'Retour de marchandise non identifié ou mal orienté', 'conformity', 'le retour, les références, le motif et les décisions de traitement disponibles'],
    ['quarantine', 'Marchandise bloquée remise en stock disponible', 'procedure', 'le lot, le motif de blocage, les statuts et les mouvements enregistrés'],
    ['inventory', 'Inventaire non réalisé ou rapprochement incomplet', 'procedure', 'les zones, les dates de comptage et les écarts non rapprochés'],
    ['packing', 'Colis mal emballé ou protection insuffisante', 'conformity', 'la commande, le conditionnement attendu et les défauts ou dommages constatés'],
    ['capacity', 'Saturation d’entrepôt ou de zone de préparation', 'improvement', 'les volumes entrants, les emplacements occupés et les capacités de traitement'],
    ['automation', 'Convoyeur ou système de préparation indisponible', 'delay', 'l’équipement, la durée d’arrêt et les commandes ou flux affectés'],
    ['handoff', 'Transfert de responsabilité entre plateformes non tracé', 'document', 'les plateformes, les mouvements, les horaires et les preuves de prise en charge'],
  ],
  retail: [
    ['price', 'Prix affiché différent du prix facturé', 'conformity', 'la référence, les prix affiché et facturé, la date et les justificatifs disponibles'],
    ['promotion', 'Promotion ou condition commerciale mal appliquée', 'complaint', 'l’offre, les conditions annoncées, la transaction et la demande du client'],
    ['payment', 'Erreur d’encaissement ou paiement non rapproché', 'conformity', 'la transaction, le moyen de paiement et les écarts de rapprochement sans données bancaires inutiles'],
    ['fraud', 'Suspicion de fraude ou de détournement en point de vente', 'risk', 'les écarts factuels, les opérations concernées et le signalement confidentiel au responsable'],
    ['recall', 'Produit faisant l’objet d’un retrait encore proposé à la vente', 'procedure', 'la référence, les lots visés, les consignes de retrait et les quantités en rayon'],
    ['warranty', 'Demande de garantie non traitée', 'complaint', 'le produit, les engagements de garantie, la date de demande et les échanges disponibles'],
    ['online', 'Fiche produit en ligne incorrecte ou trompeuse', 'conformity', 'la fiche, les informations attendues et les écarts entre la description et le produit'],
    ['click-collect', 'Commande à retirer non disponible au créneau prévu', 'delay', 'la commande, le créneau confirmé et les étapes de préparation ou de mise à disposition'],
    ['queue', 'Temps d’attente client excessif en magasin', 'measurement', 'les plages horaires, les temps d’attente mesurés et les moyens d’accueil disponibles'],
    ['shelf', 'Produit rangé dans un emplacement de vente incorrect', 'conformity', 'la référence, le rayon attendu et les erreurs d’emplacement ou de signalétique'],
    ['invoice', 'Facture ou ticket de vente incorrect', 'conformity', 'le justificatif, les articles, les montants et les corrections demandées'],
    ['loyalty', 'Avantage fidélité ou bon d’achat non pris en compte', 'complaint', 'l’avantage annoncé, ses conditions et la transaction concernée sans identifiants inutiles'],
    ['safety', 'Risque de chute ou d’obstacle dans un point de vente', 'risk', 'la zone accessible au public, les obstacles et les signalements réalisés'],
    ['demonstration', 'Conseil ou démonstration produit non maîtrisés', 'training', 'le produit, les compétences requises et les difficultés de conseil observées'],
    ['after-sales', 'Délai de service après-vente dépassé', 'delay', 'la demande, le délai annoncé et les étapes en attente chez les intervenants'],
  ],
  health: [
    ['medication', 'Écart signalé dans le circuit du médicament', 'conformity', 'l’étape du circuit, l’écart observé et les références utiles, sans donnée de santé nominative inutile'],
    ['fall', 'Chute d’un patient ou d’un résident signalée', 'accident', 'le lieu et les circonstances selon le protocole interne, sans remplacer la prise en charge'],
    ['sterilization', 'Preuve de stérilisation ou de désinfection absente', 'document', 'le matériel, le cycle, les contrôles et les preuves manquantes'],
    ['infection', 'Suspicion de risque infectieux dans un service', 'risk', 'les observations et la zone concernée, selon le protocole de signalement au personnel compétent'],
    ['handover', 'Transmission entre équipes de soins incomplète', 'conformity', 'les informations attendues, la période et les écarts de transmission sans identité inutile'],
    ['consent', 'Document d’information ou de consentement manquant', 'document', 'la pièce requise, l’étape de prise en charge et les preuves disponibles sans contenu médical inutile'],
    ['delay', 'Retard de prise en charge ou de rendez-vous', 'delay', 'les délais prévus, les délais constatés et les étapes du parcours affectées'],
    ['equipment-check', 'Vérification périodique d’un dispositif médical dépassée', 'procedure', 'le dispositif, les échéances et les justificatifs de vérification'],
    ['supply', 'Rupture de consommable nécessaire à la prise en charge', 'supplier', 'la référence, les besoins, le stock et les engagements d’approvisionnement'],
    ['nutrition', 'Écart au plan d’accompagnement nutritionnel', 'conformity', 'la consigne validée et l’écart de prestation, sans prescription ni donnée personnelle inutile'],
    ['confidentiality', 'Accès injustifié à une information de santé', 'risk', 'la catégorie d’information, l’accès constaté et le signalement confidentiel au responsable compétent'],
    ['restraint', 'Écart aux règles internes de protection des personnes', 'risk', 'la règle applicable et les faits signalés par le canal interne approprié'],
    ['emergency', 'Dispositif interne d’alerte non fonctionnel', 'risk', 'le dispositif, les tests et les dysfonctionnements signalés selon les consignes d’urgence'],
    ['mobility', 'Matériel de transfert ou d’aide à la mobilité défectueux', 'conformity', 'le matériel, les contrôles et les défauts signalés au personnel compétent'],
    ['dignity', 'Réclamation concernant l’accueil ou la dignité', 'complaint', 'les faits rapportés et les engagements d’accueil, sans détails personnels superflus'],
  ],
  laboratory: [
    ['chain', 'Chaîne de possession d’un échantillon interrompue', 'document', 'l’identifiant, les transferts, les horaires et les signatures ou validations manquantes'],
    ['transport', 'Conditions de transport d’un échantillon non respectées', 'conformity', 'l’échantillon, les délais, les conditions enregistrées et les critères de réception'],
    ['volume', 'Volume ou quantité d’échantillon insuffisants', 'conformity', 'la quantité reçue, la méthode prévue et les critères d’acceptation'],
    ['contamination', 'Contamination suspectée d’un échantillon', 'conformity', 'les observations, les manipulations et les contrôles disponibles sans conclure prématurément'],
    ['control', 'Contrôle qualité analytique hors limites', 'conformity', 'la série, les matériaux de contrôle, les valeurs et les limites d’acceptation'],
    ['proficiency', 'Résultat d’essai interlaboratoires non satisfaisant', 'audit', 'l’exercice, les résultats, les critères d’évaluation et les écarts relevés'],
    ['validation', 'Méthode analytique utilisée sans validation suffisante', 'procedure', 'la méthode, son domaine d’emploi et les preuves de validation disponibles'],
    ['uncertainty', 'Incertitude de mesure non évaluée ou non actualisée', 'document', 'la mesure, les sources de variation et les éléments de calcul documentés'],
    ['transcription', 'Erreur de transcription d’un résultat d’analyse', 'conformity', 'le résultat source, le rapport diffusé et les étapes de transcription'],
    ['report', 'Rapport d’essai diffusé sans validation requise', 'procedure', 'le rapport, les validations attendues et les destinataires concernés'],
    ['storage', 'Conservation d’échantillons hors conditions définies', 'conformity', 'les échantillons, les conditions enregistrées et les durées de conservation'],
    ['reference', 'Matériau de référence absent ou périmé', 'conformity', 'la référence, le certificat, la date limite et les analyses concernées'],
    ['software', 'Calcul analytique ou paramétrage logiciel incorrect', 'conformity', 'la version, les paramètres, les données sources et les résultats affectés'],
    ['disposal', 'Élimination d’un échantillon avant la durée prévue', 'procedure', 'l’échantillon, la date d’élimination et les exigences de conservation'],
    ['authorization', 'Analyse réalisée hors domaine de compétence autorisé', 'training', 'l’analyse, les habilitations attendues et les preuves de compétence'],
  ],
  technology: [
    ['access', 'Droits informatiques trop larges ou mal attribués', 'risk', 'les rôles, les accès attendus et les écarts observés, sans partager de secrets'],
    ['backup', 'Sauvegarde échouée ou restauration non testée', 'risk', 'les systèmes, les dates de sauvegarde et les résultats des tests de restauration'],
    ['performance', 'Temps de réponse ou performance dégradés', 'measurement', 'les opérations, les temps mesurés, la charge et la période de comparaison'],
    ['integration', 'Échange entre applications ou API en échec', 'conformity', 'les applications, les messages d’erreur expurgés et les transactions affectées'],
    ['migration', 'Migration de données incomplète ou incorrecte', 'conformity', 'les jeux de données, les contrôles de rapprochement et les écarts après migration'],
    ['regression', 'Régression après mise à jour logicielle', 'conformity', 'les versions avant et après, les scénarios affectés et les preuves de reproduction'],
    ['test', 'Tests requis absents avant une mise en production', 'procedure', 'la livraison, les scénarios attendus et les résultats ou validations manquants'],
    ['certificate', 'Certificat ou licence technique arrivé à expiration', 'delay', 'la ressource, la date d’expiration et les services dépendants'],
    ['monitoring', 'Alerte informatique non détectée ou non transmise', 'conformity', 'l’événement, les règles d’alerte et les horaires de détection ou de notification'],
    ['capacity', 'Capacité de stockage ou ressources système saturées', 'risk', 'les ressources, les seuils, la tendance d’utilisation et les services exposés'],
    ['phishing', 'Suspicion d’hameçonnage ou d’incident cyber', 'risk', 'les faits observés et le signalement au référent compétent, sans diffuser de contenu sensible'],
    ['secrets', 'Information sensible exposée dans un fichier ou journal', 'risk', 'la catégorie d’information, l’emplacement et les accès possibles, sans recopier le secret'],
    ['compatibility', 'Incompatibilité avec un navigateur ou terminal', 'conformity', 'le terminal, le navigateur, la version et les étapes de reproduction'],
    ['accessibility', 'Interface numérique inaccessible à certains utilisateurs', 'conformity', 'le parcours, les critères attendus et les difficultés d’usage constatées'],
    ['rollback', 'Retour arrière de déploiement indisponible ou non testé', 'risk', 'la livraison, les dépendances et les preuves de test du retour arrière'],
  ],
  education: [
    ['registration', 'Inscription ou dossier apprenant incorrect', 'conformity', 'la session, les pièces attendues et les erreurs de dossier sans données personnelles inutiles'],
    ['prerequisite', 'Prérequis d’entrée en formation non vérifiés', 'procedure', 'les prérequis, les critères d’entrée et les vérifications réalisées'],
    ['materials', 'Supports pédagogiques obsolètes ou incomplets', 'document', 'le module, la version du support et les notions manquantes ou erronées'],
    ['exam', 'Organisation d’examen non conforme aux règles', 'procedure', 'l’épreuve, les règles, les convocations et les écarts de déroulement'],
    ['grading', 'Barème ou correction appliqués de façon incohérente', 'conformity', 'l’évaluation, le barème validé et les écarts entre corrections anonymisées'],
    ['certificate', 'Attestation ou certificat délivrés avec une erreur', 'conformity', 'la session, les mentions attendues et les erreurs du document délivré'],
    ['dropout', 'Abandons ou absences d’apprenants en hausse', 'measurement', 'la période, les effectifs, les taux d’absence et les motifs recueillis sans détails sensibles'],
    ['adaptation', 'Adaptation pédagogique prévue non réalisée', 'conformity', 'l’adaptation convenue, les moyens prévus et l’écart sans donnée de santé inutile'],
    ['distance', 'Plateforme de formation à distance indisponible', 'delay', 'la session, la durée d’indisponibilité et les activités pédagogiques affectées'],
    ['internship', 'Suivi de stage ou d’alternance incomplet', 'document', 'les engagements de suivi, les dates et les comptes rendus manquants'],
    ['safety', 'Consigne de sécurité en atelier pédagogique non respectée', 'procedure', 'l’atelier, les équipements et les écarts aux consignes applicables'],
    ['bullying', 'Signalement de violence ou de harcèlement dans une formation', 'risk', 'les faits transmis par le canal de protection approprié, sans détails identifiants inutiles'],
    ['evaluation', 'Évaluation de fin de formation non recueillie', 'measurement', 'la session, les réponses attendues et le taux de recueil disponible'],
    ['trainer-delay', 'Intervenant absent ou remplacement non organisé', 'delay', 'la session, le créneau et les solutions de remplacement disponibles'],
    ['funding', 'Justificatifs de financement de formation manquants', 'document', 'le dossier, les pièces demandées et les échéances de transmission'],
  ],
  hospitality: [
    ['overbooking', 'Surréservation ou capacité d’accueil dépassée', 'conformity', 'les réservations confirmées, les capacités et les prestations non disponibles'],
    ['billing', 'Erreur de facturation d’un séjour ou d’une prestation', 'conformity', 'les prestations convenues, les montants facturés et les justificatifs disponibles'],
    ['noise', 'Nuisance sonore signalée par un client accueilli', 'complaint', 'la zone, les horaires, les faits rapportés et les réponses déjà apportées'],
    ['lost-property', 'Objet confié ou oublié non retrouvé', 'complaint', 'la date, le lieu et les enregistrements de prise en charge, sans information personnelle inutile'],
    ['key', 'Clé ou accès d’hébergement attribués incorrectement', 'risk', 'l’accès concerné, les attributions et les contrôles prévus sans divulguer de codes'],
    ['linen', 'Linge fourni sale, manquant ou non conforme', 'conformity', 'les espaces, les quantités et les critères de qualité du linge'],
    ['pests', 'Présence de nuisibles dans un hébergement', 'risk', 'la zone, les observations et les signalements au personnel compétent'],
    ['pool', 'Contrôle d’un bassin ou espace de baignade non conforme', 'risk', 'le bassin, les résultats de contrôle et les limites applicables au site'],
    ['fire', 'Issue de secours ou dispositif incendie non conforme', 'risk', 'la zone, les contrôles et les anomalies transmises selon les consignes du site'],
    ['accessibility', 'Prestation d’accueil accessible promise non disponible', 'conformity', 'la prestation annoncée, la réservation et les équipements effectivement disponibles'],
    ['activity', 'Activité ou excursion annoncée non assurée', 'complaint', 'la prestation vendue, le programme et les écarts constatés'],
    ['check-in', 'Temps d’attente excessif à l’arrivée ou au départ', 'measurement', 'les créneaux, les temps mesurés et les ressources d’accueil disponibles'],
    ['water', 'Eau chaude ou équipement sanitaire indisponibles', 'conformity', 'les espaces concernés, la durée et les défauts constatés'],
    ['privacy', 'Information de réservation divulguée sans justification', 'risk', 'la catégorie d’information et les circonstances signalées au responsable compétent'],
    ['contractor', 'Prestation d’accueil externalisée non conforme', 'supplier', 'le prestataire, les engagements et les écarts relevés lors du contrôle'],
  ],
  environment: [
    ['hazardous', 'Déchet dangereux mélangé à un flux non compatible', 'risk', 'le flux, les observations et les consignes de signalement au personnel compétent'],
    ['manifest', 'Bordereau ou justificatif de traitement absent', 'document', 'le déchet, le mouvement et les justificatifs attendus à chaque étape'],
    ['container', 'Bac ou conteneur de collecte endommagé', 'conformity', 'le contenant, le site, les défauts et les opérations affectées'],
    ['odor', 'Nuisance olfactive signalée autour d’un site', 'complaint', 'le lieu, la période, les activités du site et les réclamations reçues'],
    ['noise', 'Niveau sonore environnemental hors référence', 'measurement', 'les points de mesure, les horaires, les résultats et les valeurs de référence'],
    ['air', 'Résultat de contrôle des émissions atmosphériques défavorable', 'conformity', 'le point de mesure, la méthode, les résultats et les exigences applicables'],
    ['sludge', 'Boue ou résidu de traitement hors spécification', 'conformity', 'le lot, les analyses et les critères d’acceptation de la filière prévue'],
    ['overflow', 'Débordement ou saturation d’un ouvrage de traitement', 'risk', 'l’ouvrage, les événements, les volumes connus et les alertes enregistrées'],
    ['sampling', 'Prélèvement environnemental réalisé hors protocole', 'procedure', 'le point, la date, le protocole et les conditions réelles de prélèvement'],
    ['discharge', 'Autorisation ou suivi d’un rejet incomplets', 'document', 'le rejet, les documents applicables et les contrôles ou déclarations manquants'],
    ['recycling', 'Taux de valorisation des déchets en baisse', 'measurement', 'les tonnages entrants, les quantités valorisées et les périodes comparées'],
    ['illegal', 'Dépôt de déchets non autorisé sur un site', 'risk', 'le lieu, les observations et le signalement au responsable, sans manipulation improvisée'],
    ['leachate', 'Gestion des eaux de ruissellement non maîtrisée', 'risk', 'les zones, les ouvrages, les événements météorologiques et les observations disponibles'],
    ['equipment', 'Équipement de traitement indisponible', 'delay', 'l’équipement, la durée d’arrêt et les flux ou contrôles affectés'],
    ['permit', 'Échéance de suivi environnemental non respectée', 'delay', 'l’obligation de suivi, l’échéance et les justificatifs de réalisation disponibles'],
  ],
  energy: [
    ['voltage', 'Qualité de fourniture ou tension hors référence', 'conformity', 'le point de fourniture, les mesures et les engagements de qualité applicables'],
    ['meter', 'Compteur ou relevé énergétique incohérent', 'conformity', 'le compteur, la période, les relevés et les consommations de comparaison'],
    ['leak', 'Suspicion de fuite sur une installation énergétique', 'risk', 'les observations et la localisation transmises selon les consignes d’alerte du site'],
    ['isolation', 'Consignation ou remise en service mal tracées', 'procedure', 'l’installation, les autorisations et les preuves des étapes de consignation'],
    ['renewable', 'Production renouvelable inférieure aux prévisions', 'measurement', 'les données de production, les conditions et la période de référence'],
    ['battery', 'Défaut ou alerte sur un système de stockage d’énergie', 'risk', 'l’équipement, les alertes et les observations signalées au personnel habilité'],
    ['connection', 'Raccordement non conforme au dossier validé', 'conformity', 'le dossier, les contrôles et les écarts constatés sur le raccordement'],
    ['commissioning', 'Mise en service sans validation requise', 'procedure', 'l’installation, les essais attendus et les validations disponibles'],
    ['inspection', 'Inspection réglementaire d’installation non démontrée', 'document', 'l’installation, les échéances et les rapports ou justificatifs manquants'],
    ['remote', 'Défaut de télésurveillance d’une installation', 'conformity', 'les signaux, les horaires et les événements non remontés au suivi'],
    ['heat', 'Température de réseau ou fourniture de chaleur non conforme', 'conformity', 'les points de mesure, les températures et les engagements de fourniture'],
    ['outage', 'Coupures énergétiques récurrentes', 'recurring', 'les dates, les durées, les installations et les actions déjà réalisées'],
    ['billing', 'Facturation énergétique contestée', 'complaint', 'la période, les relevés, les montants facturés et les éléments de contestation'],
    ['efficiency', 'Rendement énergétique d’un équipement en baisse', 'measurement', 'les consommations, les productions utiles et les périodes de comparaison'],
    ['contractor', 'Intervention énergétique externe non conforme', 'supplier', 'la prestation, les habilitations attendues et les écarts au cahier des charges'],
  ],
  finance: [
    ['payment', 'Paiement exécuté en double ou vers un mauvais bénéficiaire', 'conformity', 'les références de transaction et les contrôles disponibles, sans recopier de coordonnées sensibles'],
    ['reconciliation', 'Écart de rapprochement comptable ou bancaire', 'conformity', 'la période, les écritures et les justificatifs présentant un écart'],
    ['closing', 'Clôture comptable réalisée hors délai', 'delay', 'la période, le calendrier de clôture et les tâches ou validations en attente'],
    ['tax', 'Déclaration administrative ou fiscale erronée', 'conformity', 'la déclaration, la période, les données sources et les écarts vérifiés par le référent compétent'],
    ['identity', 'Vérification d’identité ou de dossier non démontrée', 'procedure', 'les contrôles requis et les preuves disponibles sans copie inutile de pièces personnelles'],
    ['fraud', 'Suspicion de fraude dans une opération financière', 'risk', 'les écarts factuels et le signalement confidentiel au responsable habilité'],
    ['authorization', 'Opération validée hors délégation autorisée', 'procedure', 'l’opération, les seuils et les délégations applicables au moment de la validation'],
    ['contract', 'Condition contractuelle mal appliquée', 'conformity', 'la clause, sa version et les écarts entre l’engagement et le traitement réalisé'],
    ['claim-delay', 'Réclamation financière non traitée dans le délai prévu', 'delay', 'la date de réception, le délai applicable et les échanges ou réponses disponibles'],
    ['archive', 'Durée ou conditions de conservation d’un dossier non respectées', 'document', 'le dossier, la règle de conservation et les preuves de stockage ou de suppression'],
    ['conflict', 'Conflit d’intérêts potentiel non déclaré', 'risk', 'la situation et les exigences de déclaration, en utilisant le canal confidentiel prévu'],
    ['report', 'Rapport financier diffusé avec des données incohérentes', 'conformity', 'la version, les sources et les incohérences de montants ou de période'],
    ['fees', 'Frais ou commissions contestés par un client', 'complaint', 'les conditions annoncées, les frais appliqués et les motifs de contestation'],
    ['segregation', 'Séparation des tâches de contrôle insuffisante', 'risk', 'les opérations, les rôles et les validations réalisées par une même personne'],
    ['forecast', 'Prévision de trésorerie ou de charge non fiable', 'measurement', 'les hypothèses, les prévisions et les résultats observés sur la même période'],
  ],
  services: [
    ['contract', 'Engagement contractuel non respecté dans une mission', 'conformity', 'la clause, les livrables et les preuves de réalisation de la prestation'],
    ['validation', 'Livrable remis sans validation convenue', 'procedure', 'le livrable, les étapes de validation et les preuves d’accord disponibles'],
    ['version', 'Mauvaise version d’un livrable transmise au client', 'document', 'la référence, les versions et les destinataires du document transmis'],
    ['appointment', 'Rendez-vous oublié ou intervenant absent', 'delay', 'le rendez-vous confirmé, le créneau et les conséquences sur la prestation'],
    ['billing', 'Facturation d’une prestation incorrecte ou contestée', 'complaint', 'la commande, les prestations réalisées et les montants ou postes contestés'],
    ['access', 'Accès au site client indisponible pour une intervention', 'delay', 'l’intervention, le créneau et les autorisations d’accès attendues'],
    ['equipment', 'Matériel nécessaire à une prestation indisponible', 'delay', 'la prestation, le matériel prévu et les alternatives déjà validées'],
    ['rework', 'Reprises de prestation trop fréquentes', 'recurring', 'les missions, les reprises, les motifs et les corrections déjà tentées'],
    ['acceptance', 'Critères d’acceptation d’un livrable non définis', 'document', 'le livrable, les attentes du client et les critères d’acceptation manquants'],
    ['estimate', 'Estimation de charge ou devis inadaptés au besoin', 'conformity', 'le besoin, les hypothèses du devis et les écarts de charge constatés'],
    ['scope-change', 'Modification de prestation sans accord formalisé', 'procedure', 'la demande de changement, les impacts et les accords disponibles'],
    ['complaint-followup', 'Réponse au client non suivie ou contradictoire', 'complaint', 'les demandes, les réponses envoyées et les engagements contradictoires'],
    ['remote', 'Prestation à distance interrompue ou inaccessible', 'conformity', 'la prestation, la durée d’interruption et les difficultés d’accès rapportées'],
    ['handover-file', 'Dossier de fin de mission incomplet', 'document', 'les pièces convenues, les livrables remis et les documents absents'],
    ['travel', 'Organisation des déplacements d’intervention insuffisante', 'improvement', 'les sites, les créneaux, les temps de déplacement et les conflits d’organisation'],
  ],
  security: [
    ['badge', 'Badge ou autorisation d’accès attribués incorrectement', 'risk', 'les droits attendus, les attributions et les écarts, sans divulguer de codes d’accès'],
    ['visitor', 'Registre de visiteurs incomplet', 'document', 'la période, les champs requis et les enregistrements manquants sans identité inutile'],
    ['alarm', 'Alarme non traitée ou traitement mal tracé', 'conformity', 'l’événement, les horaires, les consignes et les preuves de prise en charge'],
    ['camera', 'Dispositif de surveillance indisponible', 'conformity', 'l’équipement, la période d’indisponibilité et les contrôles techniques disponibles'],
    ['keys', 'Clé ou moyen d’accès confié non retrouvé', 'risk', 'le moyen d’accès, les mouvements enregistrés et les responsables alertés'],
    ['handover', 'Relève de poste de sécurité incomplète', 'conformity', 'les consignes à transmettre, la relève et les informations absentes'],
    ['post', 'Poste de surveillance laissé sans couverture', 'risk', 'le poste, la plage horaire et l’organisation de remplacement prévue'],
    ['emergency', 'Consigne d’alerte ou d’évacuation non maîtrisée', 'training', 'les missions, les consignes et les résultats des exercices ou formations'],
    ['fire', 'Contrôle incendie prévu non effectué', 'procedure', 'le contrôle, l’échéance et les preuves de vérification disponibles'],
    ['intrusion', 'Intrusion ou tentative d’accès non autorisé signalée', 'risk', 'le lieu, l’heure et les faits transmis selon le protocole interne de signalement'],
    ['confidentiality', 'Image ou information de surveillance divulguée', 'risk', 'la catégorie d’information et les circonstances signalées par le canal confidentiel prévu'],
    ['qualification', 'Autorisation professionnelle ou habilitation non vérifiée', 'document', 'la mission, les justificatifs requis et leurs dates de validité'],
    ['radio', 'Moyen de communication d’un agent défaillant', 'conformity', 'l’équipement, les tests et les missions affectées par la défaillance'],
    ['contract', 'Couverture de sécurité différente du contrat', 'conformity', 'le contrat, les postes et les plages horaires effectivement couverts'],
    ['false-alarm', 'Fausses alertes de sécurité récurrentes', 'recurring', 'les événements, leur fréquence et les vérifications ou corrections déjà réalisées'],
  ],
};

export const SECTOR_SITUATIONS = {
  agriculture: [
    ['organic', 'Mélange de récoltes sous certifications différentes', 'conformity', 'les certifications, les parcelles, les lots et les mouvements concernés'],
    ['lease', 'Exigence de parcelle ou d’exploitation non documentée', 'document', 'la parcelle, les engagements applicables et les justificatifs manquants'],
  ],
  'food-industry': [
    ['line-clearance', 'Vide de ligne alimentaire non vérifié avant changement de produit', 'food', 'les produits successifs, les emballages restants et les contrôles de changement de série'],
    ['shelf-life', 'Durée de conservation alimentaire non justifiée', 'food', 'la recette, le conditionnement, les études et les conditions de conservation validées'],
  ],
  airport: [
    ['baggage', 'Bagage orienté vers une mauvaise destination', 'conformity', 'les références de suivi, les étapes de transfert et la destination attendue sans identité inutile'],
    ['turnaround', 'Coordination de rotation aéroportuaire insuffisante', 'delay', 'les jalons de rotation, les prestations attendues et les retards de coordination'],
  ],
  craft: [
    ['custom', 'Réalisation artisanale différente du modèle validé', 'conformity', 'le modèle accepté, les dimensions, les matériaux et les écarts de réalisation'],
    ['quote', 'Commande artisanale acceptée avec un devis incomplet', 'document', 'le devis, les options convenues et les informations nécessaires à la réalisation'],
  ],
  insurance: [
    ['coverage', 'Garantie d’assurance mal expliquée ou mal appliquée', 'complaint', 'les conditions du contrat, la garantie concernée et les échanges avec le client'],
    ['claim', 'Pièce de dossier de sinistre non prise en compte', 'conformity', 'les pièces reçues, les dates et les étapes de traitement sans détails personnels inutiles'],
  ],
  automotive: [
    ['torque', 'Couple de serrage automobile non enregistré ou non conforme', 'conformity', 'les assemblages, les valeurs prescrites, les mesures et les outils utilisés'],
    ['recall', 'Traçabilité de composants insuffisante pour une campagne automobile', 'document', 'les références, les lots et les liens entre composants et produits concernés'],
  ],
  aviation: [
    ['configuration', 'Configuration aéronautique différente du dossier approuvé', 'conformity', 'la référence, la configuration approuvée et les écarts documentés par le personnel habilité'],
    ['part', 'Justificatif de conformité d’une pièce aéronautique absent', 'document', 'la pièce, le numéro de série et les preuves de conformité attendues'],
  ],
  banking: [
    ['account', 'Demande d’ouverture ou de clôture de compte mal traitée', 'conformity', 'la demande, les délais et les étapes de vérification sans coordonnées sensibles inutiles'],
    ['transfer', 'Ordre bancaire traité sans contrôle requis', 'procedure', 'la référence de l’ordre, les contrôles attendus et les validations disponibles'],
  ],
  construction: [
    ['building-access', 'Accès ou cheminement de bâtiment non conforme au projet', 'conformity', 'les plans, les cheminements et les écarts constatés lors de la réception'],
    ['interface', 'Interface entre corps d’état mal réalisée', 'conformity', 'les lots de travaux, les plans de coordination et les défauts de raccordement'],
  ],
  beauty: [
    ['service', 'Prestation esthétique différente de la demande validée', 'complaint', 'la prestation convenue, les produits utilisés et les faits rapportés par le client'],
    ['reaction', 'Réaction indésirable signalée après une prestation de beauté', 'risk', 'la prestation, les références des produits et le signalement au professionnel compétent sans conseil médical'],
  ],
  bakery: [
    ['fermentation', 'Fermentation ou levée de pâte non maîtrisée', 'food', 'la recette, les lots, les horaires et les paramètres enregistrés de fermentation'],
    ['baking', 'Défaut de cuisson ou de texture en boulangerie', 'conformity', 'le produit, le lot, les réglages enregistrés et les critères de qualité attendus'],
  ],
  butchery: [
    ['origin', 'Origine ou identification de viande non démontrées', 'document', 'les lots, les documents fournisseur et les liens de traçabilité disponibles'],
    ['cutting', 'Séparation des opérations de découpe non respectée', 'food', 'les produits, les postes de découpe et les consignes de séparation applicables'],
  ],
  wood: [
    ['moisture', 'Humidité du bois incompatible avec l’usage prévu', 'conformity', 'les essences, les mesures d’humidité et les conditions d’utilisation prévues'],
    ['dust', 'Aspiration de poussières de bois défaillante', 'risk', 'les postes, les contrôles d’aspiration et les défauts signalés selon les consignes internes'],
  ],
  chemical: [
    ['tank', 'Identification de cuve pétrochimique incorrecte', 'risk', 'les cuves, les produits et les écarts d’identification signalés au personnel compétent'],
    ['batch-release', 'Dossier de libération chimique incomplet', 'document', 'le lot, les résultats requis et les validations absentes du dossier'],
  ],
  retail: [
    ['opening', 'Contrôle d’ouverture ou de fermeture du magasin incomplet', 'procedure', 'les vérifications prévues, la date et les éléments non réalisés'],
    ['pickup', 'Article réservé remis à un mauvais client', 'conformity', 'la réservation et les contrôles de remise, sans identité personnelle inutile'],
  ],
  wholesale: [
    ['minimum', 'Conditionnement ou minimum de commande grossiste mal appliqués', 'conformity', 'les conditions convenues, les unités commandées et les quantités livrées'],
    ['allocation', 'Répartition de stock entre clients professionnels incorrecte', 'conformity', 'les commandes, les priorités convenues et les quantités affectées'],
  ],
  consulting: [
    ['assumption', 'Hypothèse d’étude ou de conseil non validée', 'conformity', 'l’hypothèse, les sources utilisées et les validations attendues dans la mission'],
    ['independence', 'Indépendance d’une mission de conseil non évaluée', 'risk', 'la mission, les critères d’indépendance et les déclarations prévues'],
  ],
  accounting: [
    ['entry', 'Écriture comptable imputée au mauvais compte', 'conformity', 'la pièce, l’écriture, l’imputation attendue et la période concernée'],
    ['payroll', 'Écart dans un traitement de paie', 'conformity', 'la règle appliquée, la période et les écarts vérifiés, sans données salariales nominatives inutiles'],
  ],
  cosmetics: [
    ['formula', 'Composition cosmétique différente de la formule validée', 'conformity', 'la formule, les ingrédients, le lot et les résultats de contrôle'],
    ['claim', 'Allégation cosmétique non étayée par les preuves prévues', 'document', 'l’allégation, le produit et les justificatifs attendus par le référent compétent'],
  ],
  culture: [
    ['ticket', 'Billet culturel ou placement attribués incorrectement', 'conformity', 'la séance, les catégories de places et les écarts de réservation'],
    ['artwork', 'Œuvre ou matériel culturel endommagés lors d’une prestation', 'conformity', 'l’objet, les constats de prise en charge et les circonstances du dommage'],
  ],
  'home-care': [
    ['visit', 'Passage à domicile prévu non réalisé', 'delay', 'le créneau, la prestation et les transmissions sans information personnelle sensible inutile'],
    ['handover', 'Consigne d’accompagnement à domicile non transmise', 'conformity', 'la consigne validée, les intervenants et les preuves de transmission'],
  ],
  electronics: [
    ['esd', 'Protection contre les décharges électrostatiques non respectée', 'procedure', 'la zone, les composants et les contrôles des protections prévues'],
    ['firmware', 'Version de firmware chargée incorrectement en fabrication', 'conformity', 'la référence, la version attendue et les unités ou lots programmés'],
  ],
  breeding: [
    ['milk', 'Enregistrement de production animale incohérent', 'conformity', 'les volumes, les périodes et les liens avec les groupes ou lots de production'],
    ['movement-plan', 'Organisation des lots d’élevage non respectée', 'procedure', 'les groupes, les mouvements et les consignes d’organisation applicables'],
  ],
  energy: [
    ['forecast', 'Prévision de fourniture énergétique inadaptée', 'measurement', 'les hypothèses, les besoins et les écarts entre prévision et fourniture'],
    ['asset', 'Identification d’un équipement énergétique incohérente', 'document', 'les références d’installation, les plans et les repères constatés sur site'],
  ],
  waste: [
    ['outlet', 'Filière de traitement de déchets non validée', 'supplier', 'le flux, le prestataire, les critères d’acceptation et les justificatifs de la filière'],
    ['commitment', 'Engagement de valorisation de déchets non démontré', 'audit', 'l’engagement, les tonnages et les preuves de traitement ou de valorisation disponibles'],
  ],
  'medical-devices': [
    ['label', 'Notice ou identification d’un dispositif médical incorrectes', 'document', 'le dispositif, la version validée de la notice et les lots concernés'],
    ['trace', 'Traçabilité de série d’un dispositif médical incomplète', 'document', 'les références, les numéros de série et les liens de fabrication ou de distribution'],
  ],
  water: [
    ['pressure', 'Pression ou disponibilité du réseau d’eau non conformes', 'conformity', 'les points du réseau, les relevés et les périodes d’interruption ou de baisse'],
    ['treatment', 'Paramètre de traitement de l’eau hors référence', 'conformity', 'l’installation, les paramètres enregistrés et les critères de fonctionnement définis'],
  ],
  publishing: [
    ['proof', 'Impression différente du bon à tirer validé', 'conformity', 'le bon à tirer, sa version et les écarts de texte, couleur ou mise en page'],
    ['cut', 'Découpe ou façonnage d’un imprimé non conformes', 'conformity', 'le format attendu, les mesures et les lots présentant un défaut de façonnage'],
  ],
  education: [
    ['curriculum', 'Programme de formation différent de l’offre contractualisée', 'conformity', 'le programme annoncé, les séquences réalisées et les écarts de contenu'],
    ['jury', 'Composition ou validation d’un jury non démontrées', 'document', 'la session, les règles de composition et les preuves de validation du jury'],
  ],
  storage: [
    ['segregation', 'Zones de stockage dédiées non respectées', 'procedure', 'les catégories de marchandises, les emplacements et les consignes de séparation'],
    ['slot', 'Créneaux de réception d’entrepôt mal coordonnés', 'improvement', 'les rendez-vous, les flux attendus et les capacités des quais ou équipes'],
  ],
  events: [
    ['crowd', 'Capacité ou flux de public mal anticipés pour un événement', 'risk', 'les capacités autorisées, les flux prévus et les consignes du site'],
    ['technical', 'Installation technique événementielle non validée', 'procedure', 'les installations, les essais et les validations nécessaires avant l’ouverture'],
  ],
  railway: [
    ['maintenance-file', 'Dossier de maintenance ferroviaire incomplet', 'document', 'le matériel, les opérations et les preuves de contrôle attendues'],
    ['service', 'Prestation ferroviaire différente du plan validé', 'conformity', 'le plan, les services et les écarts documentés par les intervenants habilités'],
  ],
  forest: [
    ['origin', 'Origine ou certification de bois non traçables', 'document', 'les parcelles, les lots et les justificatifs de provenance ou certification'],
    ['felling', 'Risque signalé sur une zone d’exploitation forestière', 'risk', 'la zone, les opérations et les observations transmises au personnel compétent'],
  ],
  hotel: [
    ['room-status', 'Statut de chambre incorrect entre réception et ménage', 'conformity', 'la chambre, les statuts enregistrés et les contrôles avant attribution'],
    ['minibar', 'Consommation ou prestation de chambre facturée à tort', 'complaint', 'les prestations enregistrées, les justificatifs et la demande de correction'],
  ],
  'real-estate': [
    ['keys', 'Remise de clés ou état des lieux incomplets', 'document', 'les pièces attendues, les clés remises et les constats documentés'],
    ['repair', 'Demande de réparation de bâtiment non suivie', 'delay', 'la demande, la priorité, les engagements et les interventions en attente'],
  ],
  mechanical: [
    ['heat-treatment', 'Traitement thermique métallurgique hors spécification', 'conformity', 'le lot, le cycle enregistré et les résultats par rapport aux spécifications'],
    ['material-grade', 'Nuance de métal différente de celle commandée', 'supplier', 'la nuance attendue, les certificats matière et les lots reçus'],
  ],
  mining: [
    ['granulometry', 'Granulométrie de matériau extrait non conforme', 'conformity', 'le lot, les prélèvements et les résultats par rapport aux critères attendus'],
    ['dust', 'Empoussièrement ou émission de carrière non maîtrisés', 'risk', 'les zones, les mesures disponibles et les signalements selon les consignes du site'],
  ],
  it: [
    ['requirements', 'Fonctionnalité livrée différente du besoin validé', 'conformity', 'le besoin, les critères d’acceptation et les scénarios montrant l’écart'],
    ['support', 'Demande de support informatique mal catégorisée', 'conformity', 'la demande, la priorité convenue et les étapes d’orientation ou d’escalade'],
  ],
  laboratory: [
    ['scope', 'Rapport utilisant une référence d’accréditation inadaptée', 'document', 'le rapport, la portée applicable et les mentions de référence utilisées'],
    ['retention', 'Dossier brut d’essai non conservé selon les exigences', 'document', 'l’essai, les données sources et les règles de conservation applicables'],
  ],
  logistics: [
    ['forecast', 'Prévision d’approvisionnement incompatible avec la demande', 'improvement', 'les prévisions, les commandes et les écarts de disponibilité observés'],
    ['lead-time', 'Délai de bout en bout de la chaîne non maîtrisé', 'measurement', 'les étapes, leurs délais et les écarts entre engagements et réalisation'],
  ],
  maintenance: [
    ['diagnosis', 'Diagnostic de panne incomplet avant réparation', 'conformity', 'les symptômes, les contrôles effectués et les hypothèses documentées'],
    ['return', 'Équipement rendu au client sans essai de fonctionnement', 'procedure', 'la réparation, les essais requis et les résultats de contrôle avant remise'],
  ],
  marine: [
    ['container', 'Conteneur portuaire orienté vers une mauvaise zone', 'conformity', 'les références, les mouvements et les zones de destination attendues'],
    ['berth', 'Créneau d’escale ou prestation portuaire mal coordonnés', 'delay', 'les horaires d’escale, les prestations et les engagements des intervenants'],
  ],
  'medical-social': [
    ['project', 'Projet d’accompagnement non actualisé', 'document', 'les échéances et les validations attendues, sans détails personnels sensibles inutiles'],
    ['activity', 'Activité d’accompagnement convenue non réalisée', 'conformity', 'la prestation prévue, la date et les écarts de réalisation'],
  ],
  cleaning: [
    ['surface', 'Surface endommagée par une prestation de nettoyage', 'conformity', 'la surface, le produit utilisé et les consignes de compatibilité applicables'],
    ['inspection', 'Contrôle de propreté contractuel non réalisé', 'procedure', 'les zones, les critères convenus et les preuves de contrôle manquantes'],
  ],
  fishing: [
    ['catch', 'Identification de capture ou de zone de pêche incomplète', 'document', 'les lots, les dates et les justificatifs de capture ou de provenance'],
    ['water-quality', 'Paramètre d’eau d’aquaculture hors référence', 'risk', 'les bassins, les mesures et les observations transmises au professionnel compétent'],
  ],
  pharma: [
    ['release', 'Libération pharmaceutique sans preuve de validation requise', 'procedure', 'le lot, les contrôles et les validations attendues par les personnes habilitées'],
    ['deviation', 'Déviation pharmaceutique non documentée dans le dossier de lot', 'conformity', 'le lot, l’étape, les faits et les décisions prises par les responsables compétents'],
  ],
  plastics: [
    ['injection', 'Défaut d’injection ou de moulage plastique', 'conformity', 'la pièce, le moule, les paramètres enregistrés et les défauts observés'],
    ['resin', 'Matière plastique ou taux de recyclé différents du cahier des charges', 'supplier', 'la matière, les certificats et les critères de composition attendus'],
  ],
  public: [
    ['equal-treatment', 'Écart aux règles de traitement équitable des demandes', 'procedure', 'les critères de traitement et les écarts factuels, sans données personnelles inutiles'],
    ['notice', 'Information administrative au public obsolète', 'document', 'le support, les règles en vigueur et les mentions à actualiser'],
  ],
  research: [
    ['protocol', 'Modification de protocole de recherche non validée', 'procedure', 'le protocole, sa version et les étapes modifiées sans validation disponible'],
    ['reproducibility', 'Résultat de recherche non reproductible', 'conformity', 'les conditions, les données sources et les résultats des essais de reproduction'],
  ],
  restaurants: [
    ['dish', 'Plat servi différent de la commande client', 'conformity', 'la commande, le plat préparé et les écarts de transmission ou de service'],
    ['service-time', 'Temps de service en restauration excessif', 'measurement', 'les horaires de commande et de service, les couverts et les postes saturés'],
  ],
  'collective-catering': [
    ['diet', 'Repas collectif différent du régime validé', 'food', 'la consigne validée, le menu et les lots servis sans donnée de santé nominative inutile'],
    ['meal-count', 'Nombre de repas livrés différent du besoin confirmé', 'conformity', 'les effectifs confirmés, les quantités préparées et les quantités livrées'],
  ],
  health: [
    ['orientation', 'Orientation dans un parcours de soins mal coordonnée', 'conformity', 'les étapes prévues et les transmissions, sans dossier de santé nominatif inutile'],
    ['appointment-file', 'Dossier nécessaire à une consultation indisponible', 'delay', 'le créneau, les pièces attendues et les étapes de mise à disposition'],
  ],
  security: [
    ['round-proof', 'Preuve de passage sur un point de ronde incohérente', 'conformity', 'les horaires, les points prévus et les événements de contrôle disponibles'],
    ['client-order', 'Consigne client de gardiennage non validée en interne', 'document', 'la consigne, sa version et les validations nécessaires avant diffusion'],
  ],
  'business-services': [
    ['subscription', 'Niveau de service différent de l’abonnement professionnel', 'conformity', 'l’offre, les engagements et les prestations réellement fournies'],
    ['multi-site', 'Prestation différente entre plusieurs sites clients', 'measurement', 'les sites, les critères communs et les résultats de contrôle comparés'],
  ],
  sport: [
    ['equipment-check', 'Vérification d’un équipement sportif non démontrée', 'procedure', 'l’équipement, les exigences du site et les preuves de vérification disponibles'],
    ['supervision', 'Encadrement d’une activité sportive insuffisamment qualifié', 'training', 'l’activité, les compétences requises et les justificatifs de qualification'],
  ],
  telecom: [
    ['coverage', 'Couverture ou qualité de connexion différente de l’engagement', 'conformity', 'la zone, le service, les mesures et les conditions de l’engagement'],
    ['activation', 'Activation ou portabilité de ligne en retard', 'delay', 'la demande, la date annoncée et les étapes de traitement en attente'],
  ],
  textile: [
    ['size', 'Taille ou gradation textile non conformes', 'conformity', 'le modèle, les tailles, les mesures et le tableau de gradation validé'],
    ['color', 'Écart de couleur ou de solidité de teinture', 'conformity', 'les lots, les références colorimétriques et les résultats d’essais disponibles'],
  ],
  tourism: [
    ['itinerary', 'Itinéraire vendu différent des prestations réservées', 'conformity', 'le programme, les confirmations et les écarts entre vente et réservation'],
    ['travel-doc', 'Information sur les formalités de voyage incorrecte', 'document', 'les informations transmises, leurs sources et leur date de vérification'],
  ],
  'road-transport': [
    ['appointment', 'Rendez-vous de chargement routier non respecté', 'delay', 'le créneau, l’arrivée réelle et les conséquences sur le trajet'],
    ['trailer', 'Remorque affectée incompatible avec la marchandise', 'conformity', 'la marchandise, les équipements requis et les caractéristiques du moyen affecté'],
  ],
  'passenger-transport': [
    ['stop', 'Arrêt prévu non desservi ou desservi incorrectement', 'conformity', 'le trajet, l’arrêt attendu et les informations de service disponibles'],
    ['capacity', 'Capacité voyageurs différente de la réservation', 'conformity', 'la réservation, le véhicule et les places effectivement disponibles'],
  ],
  'civil-engineering': [
    ['compaction', 'Compactage ou résultat d’essai de voirie non conforme', 'conformity', 'la zone, les couches, les résultats d’essais et les critères du projet'],
    ['signage', 'Signalisation temporaire de travaux publics non conforme', 'risk', 'la zone, le plan validé et les écarts signalés au responsable du chantier'],
  ],
  general: [
    ['request', 'Demande interne orientée vers un mauvais interlocuteur', 'conformity', 'la demande, le circuit prévu et les étapes d’orientation réalisées'],
    ['coordination', 'Coordination entre activités transversales insuffisante', 'improvement', 'les activités, les dépendances et les décisions ou échéances non coordonnées'],
  ],
};
