import { getSectorProblems, getSectorRecommendations, PROBLEM_SECTORS } from './problemSectorCatalog.js';

const PROFILE_CONTEXT = {
  agriculture: 'parcelle, culture, récolte ou matériel agricole',
  animals: 'animal, élevage, installation ou intervention vétérinaire',
  food: 'produit alimentaire, lot, préparation ou service',
  construction: 'chantier, ouvrage, zone de travaux ou intervenant',
  industry: 'ligne, machine, composant ou lot de fabrication',
  chemical: 'produit, formulation, lot ou installation concernée',
  transport: 'trajet, livraison, véhicule ou opération de transport',
  logistics: 'commande, emplacement, stock ou mouvement de marchandise',
  retail: 'article, commande, point de vente ou parcours client',
  health: 'soin, accompagnement, matériel ou dossier concerné, sans information nominative inutile',
  laboratory: 'échantillon, analyse, méthode ou équipement de mesure',
  technology: 'application, version, environnement ou service informatique',
  education: 'session, apprenant, évaluation ou support pédagogique',
  hospitality: 'réservation, espace d’accueil, équipement ou prestation',
  environment: 'site, collecte, rejet, déchet ou opération de traitement',
  energy: 'installation, équipement, intervention ou fourniture d’énergie',
  finance: 'dossier, opération, justificatif ou engagement de service',
  services: 'mission, livrable, dossier ou prestation client',
  security: 'site, poste, ronde, consigne ou intervention',
};

const PROBLEM_FACTS = {
  common: {
    accident: 'les circonstances, la date, le lieu et les personnes exposées',
    corrective: 'le constat initial, les corrections déjà réalisées et le résultat attendu',
    audit: 'le constat d’audit, l’exigence concernée et les preuves observées',
    supplier: 'le fournisseur, la commande, les écarts constatés et les échanges déjà réalisés',
    training: 'la compétence attendue, la tâche concernée et les difficultés constatées',
    document: 'la référence du document, sa version et les informations manquantes ou obsolètes',
    procedure: 'la consigne applicable, l’écart observé et ses conséquences',
    recurring: 'les occurrences précédentes, leur fréquence et les corrections déjà tentées',
    conformity: 'ce qui était attendu, l’écart constaté et les produits ou prestations concernés',
    complaint: 'la demande du client, la prestation concernée et la date de réception de la réclamation',
    delay: 'l’échéance prévue, la date réelle ou estimée et les engagements affectés',
    risk: 'la situation redoutée, les personnes ou activités exposées et les mesures existantes',
    measurement: 'l’indicateur concerné, la période, les valeurs observées et la référence de comparaison',
    improvement: 'les étapes du processus, les difficultés observées et l’objectif d’amélioration',
  },
  agriculture: {
    crop: 'la parcelle, la culture, les observations et les rendements comparés',
    treatment: 'le traitement prévu, le produit utilisé, le dosage enregistré et la parcelle concernée',
    harvest: 'le lot récolté, la date de récolte et les critères non respectés',
    trace: 'les parcelles, lots, dates et enregistrements manquants',
    water: 'la source d’eau, les usages concernés et les contrôles disponibles',
    machine: 'le matériel, l’opération à réaliser et les compétences à acquérir',
    delivery: 'les dates de collecte ou d’approvisionnement prévues et les quantités affectées',
    chemical: 'le produit utilisé et les circonstances de l’exposition, selon les consignes internes de signalement',
  },
  animals: {
    feed: 'la référence de l’aliment, le lot, le fournisseur et l’écart observé',
    care: 'l’intervention prévue, l’écart constaté et les enregistrements de suivi disponibles',
    health: 'les observations, les installations concernées et les mesures sanitaires déjà en place',
    trace: 'les identifiants concernés et les informations absentes des registres',
    hygiene: 'la consigne, la zone concernée et les preuves de nettoyage disponibles',
    transport: 'le trajet, les horaires et les circonstances de l’incident',
    supplies: 'la fourniture, sa référence, le fournisseur et l’écart constaté',
    staff: 'les tâches de manipulation et les compétences attendues',
  },
  food: {
    expiry: 'la référence du produit, le lot, la DLC ou DDM, les quantités et la date de découverte',
    cold: 'les températures relevées, les horaires, la durée estimée de l’écart et les lots concernés',
    contamination: 'les observations, les produits ou lots concernés et les contrôles disponibles, sans conclure à une cause non vérifiée',
    allergen: 'l’allergène concerné, la recette ou composition attendue et l’étiquette utilisée',
    hygiene: 'la zone, le plan de nettoyage prévu, les opérations enregistrées et les écarts observés',
    cooking: 'les temps et températures enregistrés, les consignes applicables et les lots concernés',
    trace: 'les références de lots, les mouvements et les liens de traçabilité manquants',
    receipt: 'le fournisseur, le bon de livraison, les lots reçus et les écarts à réception',
    foreign: 'la nature du corps étranger observé, le produit, le lot et les circonstances de découverte',
    ccp: 'le point de contrôle, la limite définie et les valeurs réellement enregistrées',
  },
  construction: {
    work: 'l’ouvrage, la zone, les exigences prévues et les défauts constatés',
    plans: 'la référence du plan, son indice, sa validation et les équipes qui l’utilisent',
    materials: 'les matériaux, les lots, le fournisseur et les critères de réception',
    height: 'le lieu, l’opération et les circonstances de l’incident, selon le dispositif de signalement du chantier',
    deadline: 'les jalons prévus, l’avancement réel et les travaux dépendants',
    handover: 'les réserves, les zones concernées et les exigences de réception',
    subcontract: 'la prestation confiée, les engagements du sous-traitant et les écarts constatés',
    ppe: 'la consigne de sécurité applicable et les écarts observés sur le chantier',
    skills: 'l’opération prévue, l’habilitation attendue et les justificatifs disponibles',
  },
  industry: {
    dimension: 'les caractéristiques attendues, les mesures relevées et les pièces ou lots concernés',
    scrap: 'les volumes produits, les rebuts, les retouches et la période de comparaison',
    machine: 'l’équipement, les pannes précédentes et les interventions déjà réalisées',
    setting: 'les paramètres attendus, les réglages constatés et les lots produits',
    material: 'la référence du composant ou de la matière, le lot et les contrôles à réception',
    batch: 'les lots, les étapes de fabrication et les enregistrements manquants',
    inspection: 'le contrôle prévu, la fréquence attendue et les enregistrements absents',
    safety: 'la machine, l’opération et les circonstances de l’incident',
    qualification: 'l’opération de production et les compétences ou autorisations attendues',
  },
  chemical: {
    dose: 'la formulation attendue, les quantités enregistrées et le lot concerné',
    leak: 'le produit, la zone et les observations disponibles, selon les consignes internes d’alerte',
    exposure: 'le produit et les circonstances de l’exposition, sans se substituer à la prise en charge compétente',
    label: 'la référence du produit, l’étiquette utilisée et la version de la fiche de sécurité',
    storage: 'les produits, les emplacements et les exigences de stockage applicables',
    batch: 'les spécifications attendues, les résultats de contrôle et le lot concerné',
    procedure: 'la manipulation réalisée, la consigne applicable et l’écart observé',
    trace: 'le dossier, le lot et les étapes ou enregistrements manquants',
  },
  transport: {
    delivery: 'les horaires prévus et réels, le trajet et les engagements de livraison',
    damage: 'les dommages, les colis ou marchandises concernés et les constats disponibles',
    destination: 'l’adresse attendue, le destinataire enregistré et la livraison réalisée',
    loss: 'les références de colis et les derniers événements de suivi connus',
    accident: 'le trajet, le véhicule et les circonstances de l’accident',
    carrier: 'le transporteur, les engagements contractuels et les incidents constatés',
    documents: 'le document attendu, la livraison concernée et les informations incorrectes ou absentes',
    route: 'les tournées prévues, les moyens disponibles et les contraintes identifiées',
    training: 'la consigne de transport et les compétences nécessaires au conducteur',
  },
  logistics: {
    picking: 'la commande, les références et quantités attendues, les articles préparés et l’emplacement de prélèvement',
    stock: 'les références, les quantités comptées et les mouvements de stock enregistrés',
    storage: 'l’emplacement, les conditions prévues et les marchandises affectées',
    label: 'les références attendues, l’étiquette utilisée et les lots concernés',
    receipt: 'le bon de livraison, le fournisseur et les écarts de quantité ou de qualité',
    dispatch: 'les heures prévues et réelles, les commandes affectées et les étapes en attente',
    trace: 'le mouvement, le lot et les enregistrements manquants',
    handling: 'la zone, le matériel de manutention et les circonstances de l’accident',
    recurrence: 'les commandes affectées, les références confondues et les erreurs précédentes',
  },
  retail: {
    order: 'la commande du client, l’article attendu et l’article effectivement remis',
    return: 'le produit retourné, le défaut décrit et la demande du client',
    display: 'l’information annoncée, l’étiquette ou fiche produit et l’écart constaté',
    stock: 'la disponibilité annoncée, le stock constaté et les commandes affectées',
    refund: 'la demande, les engagements annoncés et les échanges avec le client',
    supplier: 'le fournisseur, les références livrées, les lots et les défauts observés',
    preparation: 'la commande en ligne, les articles attendus et le contenu préparé',
    delivery: 'le délai annoncé, la date réelle et les commandes concernées',
  },
  health: {
    identity: 'les étapes de vérification et l’écart d’identification, sans recopier de données de santé inutiles',
    care: 'l’acte ou accompagnement prévu, l’écart observé et les éléments de traçabilité nécessaires',
    hygiene: 'le protocole applicable, la zone et les pratiques observées',
    device: 'la référence du dispositif, les observations et les contrôles disponibles',
    expiry: 'la référence du produit, le lot, la date d’expiration et les quantités concernées',
    record: 'le type de dossier et les informations de traçabilité manquantes, sans données nominatives superflues',
    complaint: 'la demande du patient ou du proche et les éléments strictement nécessaires à son traitement',
    risk: 'la situation identifiée et les mesures existantes, avec les professionnels compétents',
    exposure: 'les circonstances de l’exposition selon le protocole interne, sans retarder la prise en charge',
    skills: 'la compétence attendue et les formations ou habilitations disponibles',
  },
  laboratory: {
    sample: 'l’identifiant de l’échantillon, les conditions de réception et l’écart observé',
    result: 'la méthode, les résultats observés et les critères de comparaison',
    method: 'la version du protocole et les étapes réalisées différemment',
    reagent: 'la référence du réactif, le lot et la date de validité',
    trace: 'les analyses, les échantillons et les enregistrements manquants',
    delay: 'la date promise, l’avancement de l’analyse et la date de remise réelle',
    equipment: 'l’équipement, les résultats de vérification et les mesures affectées',
    exposure: 'l’agent et les circonstances de l’exposition selon le protocole interne',
  },
  technology: {
    bug: 'la version, l’environnement, le comportement attendu et les étapes de reproduction',
    outage: 'le service, la période d’indisponibilité et les utilisateurs ou activités affectés',
    recurring: 'les incidents précédents, les versions et les corrections déjà tentées',
    data: 'les données concernées et les mesures existantes, sans copier de secrets ni de données sensibles',
    deployment: 'la version déployée, la configuration attendue et les événements constatés',
    sla: 'l’engagement de service, les horodatages et les délais de résolution constatés',
    documentation: 'la référence de la documentation, la version et les informations obsolètes',
    change: 'le changement prévu, les validations attendues et les étapes non respectées',
    provider: 'le prestataire, les engagements et les incidents attribuables à la prestation',
  },
  education: {
    training: 'les objectifs pédagogiques, le contenu prévu et les écarts constatés',
    learner: 'la demande de l’apprenant ou de la famille et la session concernée',
    attendance: 'la session, les justificatifs attendus et les preuves disponibles',
    assessment: 'les critères d’évaluation, le résultat enregistré et l’erreur constatée',
    skills: 'les compétences attendues de l’intervenant et les justificatifs disponibles',
    schedule: 'les dates annoncées, les changements et les participants affectés',
    access: 'les conditions d’accueil ou d’accès et les difficultés constatées',
    outcome: 'les résultats et retours des apprenants, la période et les objectifs prévus',
  },
  hospitality: {
    room: 'l’espace concerné, les standards attendus et les défauts constatés',
    booking: 'la réservation, les informations attendues et la prise en charge réalisée',
    cleaning: 'la zone, les critères de propreté et les constats de contrôle',
    guest: 'la prestation concernée, la demande du visiteur et les échanges déjà réalisés',
    delay: 'l’heure annoncée, la prestation attendue et le retard constaté',
    equipment: 'l’équipement, les défauts observés et les prestations affectées',
    safety: 'l’espace d’accueil, les personnes exposées et les mesures existantes',
    staff: 'les standards d’accueil et les compétences à développer',
  },
  environment: {
    sorting: 'le flux de déchets, la consigne de tri et les erreurs constatées',
    spill: 'le site, le rejet ou produit et les observations disponibles, selon les consignes internes d’alerte',
    water: 'le prélèvement, les résultats de contrôle et les critères applicables',
    trace: 'les flux, les opérations et les justificatifs de traçabilité absents',
    collection: 'la collecte prévue, la date réelle et les sites affectés',
    ppe: 'la consigne de protection et les écarts observés',
    exposure: 'les circonstances de l’exposition et les éléments nécessaires au signalement',
    provider: 'la prestation de traitement attendue et les écarts constatés',
  },
  energy: {
    supply: 'la période d’interruption, le périmètre et les engagements de fourniture',
    equipment: 'l’installation, les spécifications et les observations de contrôle',
    electrical: 'l’installation, la situation identifiée et les protections existantes',
    accident: 'l’intervention et les circonstances de l’accident selon le dispositif interne',
    maintenance: 'l’intervention prévue, l’échéance et les conséquences du retard',
    procedure: 'la consigne applicable et l’écart constaté, avec les intervenants habilités',
    skills: 'les interventions envisagées et les habilitations requises',
    trace: 'l’intervention, le contrôle et les justificatifs manquants',
  },
  finance: {
    file: 'le type de dossier et les pièces ou informations incorrectes, sans données confidentielles inutiles',
    calculation: 'les données de référence, le calcul attendu et le résultat enregistré',
    deadline: 'la date de réception, l’échéance convenue et l’avancement du dossier',
    privacy: 'le type d’information et les accès concernés, sans recopier de données sensibles',
    claim: 'la demande du client, la décision concernée et les engagements annoncés',
    procedure: 'la vérification prévue et les étapes qui n’ont pas été respectées',
    trace: 'le contrôle réalisé et les justificatifs attendus mais absents',
    recurrence: 'les opérations affectées, les erreurs précédentes et les corrections tentées',
  },
  services: {
    deliverable: 'le besoin convenu, le livrable fourni et les critères non respectés',
    delay: 'le délai promis, l’avancement et les engagements affectés',
    file: 'les informations attendues et les erreurs de traitement constatées',
    handover: 'l’information à transmettre, les intervenants et l’écart de transmission',
    scope: 'le besoin initial, les engagements et les points de désaccord du client',
    privacy: 'le type d’information et les accès concernés, sans partager de contenu confidentiel',
    provider: 'la mission confiée, les engagements et les écarts du prestataire',
    capacity: 'les tâches, les ressources disponibles et les points de surcharge',
  },
  security: {
    access: 'le site, les vérifications prévues et les écarts de contrôle constatés',
    patrol: 'la ronde prévue, les horaires et les contrôles non réalisés',
    incident: 'les faits, les horaires et les informations absentes du rapport',
    equipment: 'l’équipement de sécurité et les défauts constatés',
    response: 'l’heure d’alerte, le délai prévu et les horaires d’intervention',
    skills: 'la mission, les consignes et les compétences nécessaires',
    violence: 'les circonstances de l’agression ou de l’accident selon le dispositif interne',
    risk: 'le site, la situation redoutée et les protections existantes',
  },
};

const MODULE_STEPS = {
  accidents: { title: 'Consigner l’événement', action: 'Déclarez les circonstances et suivez l’événement' },
  risks: { title: 'Évaluer les risques', action: 'Décrivez la situation, évaluez le risque et suivez son traitement' },
  qqoqccp: { title: 'Clarifier les faits', action: 'Structurez qui, quoi, où, quand, comment, combien et pourquoi' },
  capas: { title: 'Préparer la correction durable', action: 'Si une action corrective est nécessaire, définissez son responsable, son échéance et sa vérification d’efficacité' },
  planning: { title: 'Organiser les échéances', action: 'Planifiez les tâches et les dates de suivi' },
  kpis: { title: 'Suivre l’évolution', action: 'Choisissez un indicateur et une période pour suivre le résultat des actions' },
  complaints: { title: 'Traiter la réclamation', action: 'Enregistrez la demande et suivez son traitement' },
  'customer-satisfaction': { title: 'Suivre le retour client', action: 'Consignez les retours et le niveau de satisfaction' },
  'nonconforming-outputs': { title: 'Consigner la non-conformité', action: 'Enregistrez l’écart, les éléments concernés et les décisions de traitement' },
  documents: { title: 'Retrouver les preuves', action: 'Consultez les documents et enregistrements utiles' },
  procedures: { title: 'Vérifier la consigne applicable', action: 'Consultez la procédure en vigueur et identifiez les exigences à respecter' },
  trainings: { title: 'Définir le besoin de formation', action: 'Planifiez la formation correspondant à la compétence manquante' },
  employees: { title: 'Vérifier le suivi du personnel', action: 'Consultez les informations et compétences du personnel concerné' },
  suppliers: { title: 'Évaluer le fournisseur', action: 'Examinez les engagements et consignez les résultats de l’évaluation' },
  haccp: { title: 'Examiner la maîtrise sanitaire', action: 'Consultez le plan et les contrôles HACCP associés au produit ou à l’étape concernée' },
  audits: { title: 'Examiner le constat d’audit', action: 'Consignez le constat et les preuves dans le suivi de l’audit interne' },
  pdca: { title: 'Structurer l’amélioration', action: 'Définissez les étapes de planification, réalisation, vérification et ajustement' },
};

export function getSectorProblemGuide(sectorId, problemId, access) {
  const sector = PROBLEM_SECTORS.find(({ id }) => id === sectorId);
  const problem = getSectorProblems(sectorId).find(({ id }) => id === problemId);
  if (!sector || !problem) return null;
  const [profile, key] = problem.id.split(':');
  const facts = problem.facts || PROBLEM_FACTS[profile]?.[key];
  if (!facts) throw new Error(`Guide métier manquant : ${problem.id}`);
  const contexts = (profile === 'common' || profile.startsWith('sector.') ? sector.profiles : [profile])
    .map((id) => PROFILE_CONTEXT[id]);
  const modules = getSectorRecommendations(sectorId, problemId, access);
  return {
    sector: sector.label,
    problem: problem.label,
    introduction: `Pour « ${problem.label} » dans votre activité « ${sector.label} », commencez par relier le constat à votre ${contexts.join(' ou ')}.`,
    facts,
    notice: ['accident', 'risk', 'food'].includes(problem.pathway)
      ? 'En cas de danger ou d’urgence, appliquez d’abord les consignes internes et sollicitez les personnes compétentes. Le guide organise le suivi dans le QMS, sans remplacer la prise en charge.'
      : null,
    steps: modules.slice(0, 3).map((module) => ({
      id: module.id,
      title: MODULE_STEPS[module.id].title,
      description: `${MODULE_STEPS[module.id].action} dans ${module.label}, pour traiter « ${problem.label} » dans votre secteur ${sector.label}.`,
      label: module.label,
      path: module.path,
    })),
  };
}
